/**
 * @author gianpiero.diblasi
 */
class TestJSFrame1 extends JSFrame {

   card = "card2";

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    setInterval(() => {
      this.card = this.card === "card2" ? "card3" : "card2";
      (this.jPanel4.getLayout()).show(this.jPanel4, this.card);
    }, 2000);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jLabel1 = new JSLabel();let jLabel1 = this.jLabel1;
    this.jLabel2 = new JSLabel();let jLabel2 = this.jLabel2;
    this.jLabel3 = new JSLabel();let jLabel3 = this.jLabel3;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.jLabel4 = new JSLabel();let jLabel4 = this.jLabel4;
    this.jLabel6 = new JSLabel();let jLabel6 = this.jLabel6;
    this.jLabel8 = new JSLabel();let jLabel8 = this.jLabel8;
    this.jLabel7 = new JSLabel();let jLabel7 = this.jLabel7;
    this.jLabel5 = new JSLabel();let jLabel5 = this.jLabel5;
    this.jLabel9 = new JSLabel();let jLabel9 = this.jLabel9;
    this.jPanel3 = new JSPanel();let jPanel3 = this.jPanel3;
    this.jLabel10 = new JSLabel();let jLabel10 = this.jLabel10;
    this.filler2 = new Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));let filler2 = this.filler2;
    this.jLabel11 = new JSLabel();let jLabel11 = this.jLabel11;
    this.filler1 = new Filler(new Dimension(0, 30), new Dimension(0, 30), new Dimension(32767, 30));let filler1 = this.filler1;
    this.jLabel12 = new JSLabel();let jLabel12 = this.jLabel12;
    this.filler3 = new Filler(new Dimension(0, 50), new Dimension(0, 50), new Dimension(32767, 50));let filler3 = this.filler3;
    this.jPanel4 = new JSPanel();let jPanel4 = this.jPanel4;
    this.jLabel13 = new JSLabel();let jLabel13 = this.jLabel13;
    this.jLabel14 = new JSLabel();let jLabel14 = this.jLabel14;
    this.setTitle("Test Layouts");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jLabel1.setText("jLabel1");
    jPanel1.add(jLabel1);
    jLabel2.setText("jLabel2");
    jPanel1.add(jLabel2);
    jLabel3.setText("jLabel3");
    jPanel1.add(jLabel3);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    jPanel2.setLayout(new GridLayout(2, 3, 10, 20));
    jLabel4.setText("jLabel4");
    jPanel2.add(jLabel4);
    jLabel6.setText("jLabel6");
    jPanel2.add(jLabel6);
    jLabel8.setText("jLabel8");
    jPanel2.add(jLabel8);
    jLabel7.setText("jLabel7");
    jPanel2.add(jLabel7);
    jLabel5.setText("jLabel5");
    jPanel2.add(jLabel5);
    jLabel9.setText("jLabel9");
    jPanel2.add(jLabel9);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
    jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));
    jLabel10.setText("jLabel10");
    jPanel3.add(jLabel10);
    jPanel3.add(filler2);
    jLabel11.setText("jLabel11");
    jPanel3.add(jLabel11);
    jPanel3.add(filler1);
    jLabel12.setText("jLabel12");
    jPanel3.add(jLabel12);
    jPanel3.add(filler3);
    this.getContentPane().add(jPanel3, BorderLayout.LINE_START);
    jPanel4.setLayout(new CardLayout());
    jLabel13.setBackground(new Color(204, 255, 0));
    jLabel13.setText("jLabel13");
    jPanel4.add(jLabel13, "card2");
    jLabel14.setBackground(new Color(255, 102, 153));
    jLabel14.setText("jLabel14");
    jPanel4.add(jLabel14, "card3");
    this.getContentPane().add(jPanel4, BorderLayout.LINE_END);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   filler1 = null;

   filler2 = null;

   filler3 = null;

   jLabel1 = null;

   jLabel10 = null;

   jLabel11 = null;

   jLabel12 = null;

   jLabel13 = null;

   jLabel14 = null;

   jLabel2 = null;

   jLabel3 = null;

   jLabel4 = null;

   jLabel5 = null;

   jLabel6 = null;

   jLabel7 = null;

   jLabel8 = null;

   jLabel9 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame2 extends JSFrame {

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jRadioButton5)).setToggle();
    (SwingJS.convert(this.jRadioButton6)).setToggle();
    (SwingJS.convert(this.jRadioButton7)).setToggle();
    (SwingJS.convert(this.jRadioButton8)).setToggle();
    (SwingJS.convert(this.jRadioButton9)).setToggle();
    (SwingJS.convert(this.jRadioButton10)).setToggle();
    (SwingJS.convert(this.jRadioButton11)).setToggle();
    (SwingJS.convert(this.jRadioButton12)).setToggle();
    (SwingJS.convert(this.jRadioButton13)).setToggle();
    (SwingJS.convert(this.jRadioButton14)).setToggle();
    (SwingJS.convert(this.jRadioButton15)).setToggle();
    (SwingJS.convert(this.jRadioButton16)).setToggle();
    (SwingJS.convert(this.jRadioButton17)).setToggle();
    (SwingJS.convert(this.jRadioButton18)).setToggle();
    (SwingJS.convert(this.jRadioButton19)).setToggle();
    (SwingJS.convert(this.jRadioButton20)).setToggle();
    let modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox1)).setModelAndRenderer(modelAndRendererCB);
    modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox2)).setModelAndRenderer(modelAndRendererCB);
    modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox3)).setModelAndRenderer(modelAndRendererCB);
    this.jComboBox3.setSelectedItem(30);
    modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox4)).setModelAndRenderer(modelAndRendererCB);
    this.jComboBox4.setSelectedItem(20);
    (SwingJS.convert(this.jSpinner1)).setModel(new SpinnerNumberModel(10, 5, 50, 1));
    (SwingJS.convert(this.jSpinner2)).setModel(new SpinnerNumberModel(10, 5, 50, 1));
    (SwingJS.convert(this.jButton9)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jButton13)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jButton14)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jButton15)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton9)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton10)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton11)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton12)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton13)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton14)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton15)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton16)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton13)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton14)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton15)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton16)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton17)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton18)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton19)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton20)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jCheckBox5)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jCheckBox6)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jCheckBox7)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jCheckBox8)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton21)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton22)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton23)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton24)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.buttonGroup1 = new ButtonGroup();let buttonGroup1 = this.buttonGroup1;
    this.buttonGroup2 = new ButtonGroup();let buttonGroup2 = this.buttonGroup2;
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JSButton();let jButton1 = this.jButton1;
    this.jButton2 = new JSButton();let jButton2 = this.jButton2;
    this.jButton3 = new JSButton();let jButton3 = this.jButton3;
    this.jButton4 = new JSButton();let jButton4 = this.jButton4;
    this.jButton6 = new JSButton();let jButton6 = this.jButton6;
    this.jButton7 = new JSButton();let jButton7 = this.jButton7;
    this.jButton9 = new JSButton();let jButton9 = this.jButton9;
    this.jButton13 = new JSButton();let jButton13 = this.jButton13;
    this.jButton14 = new JSButton();let jButton14 = this.jButton14;
    this.jButton15 = new JSButton();let jButton15 = this.jButton15;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.jButton5 = new JSButton();let jButton5 = this.jButton5;
    this.jRadioButton5 = new JSRadioButton();let jRadioButton5 = this.jRadioButton5;
    this.jRadioButton7 = new JSRadioButton();let jRadioButton7 = this.jRadioButton7;
    this.jRadioButton9 = new JSRadioButton();let jRadioButton9 = this.jRadioButton9;
    this.jRadioButton10 = new JSRadioButton();let jRadioButton10 = this.jRadioButton10;
    this.jRadioButton13 = new JSRadioButton();let jRadioButton13 = this.jRadioButton13;
    this.jRadioButton14 = new JSRadioButton();let jRadioButton14 = this.jRadioButton14;
    this.jRadioButton15 = new JSRadioButton();let jRadioButton15 = this.jRadioButton15;
    this.jRadioButton16 = new JSRadioButton();let jRadioButton16 = this.jRadioButton16;
    this.jButton8 = new JSButton();let jButton8 = this.jButton8;
    this.jRadioButton6 = new JSRadioButton();let jRadioButton6 = this.jRadioButton6;
    this.jRadioButton8 = new JSRadioButton();let jRadioButton8 = this.jRadioButton8;
    this.jRadioButton11 = new JSRadioButton();let jRadioButton11 = this.jRadioButton11;
    this.jRadioButton12 = new JSRadioButton();let jRadioButton12 = this.jRadioButton12;
    this.jRadioButton17 = new JSRadioButton();let jRadioButton17 = this.jRadioButton17;
    this.jRadioButton18 = new JSRadioButton();let jRadioButton18 = this.jRadioButton18;
    this.jRadioButton19 = new JSRadioButton();let jRadioButton19 = this.jRadioButton19;
    this.jRadioButton20 = new JSRadioButton();let jRadioButton20 = this.jRadioButton20;
    this.jPanel3 = new JSPanel();let jPanel3 = this.jPanel3;
    this.jButton10 = new JSButton();let jButton10 = this.jButton10;
    this.filler2 = new Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));let filler2 = this.filler2;
    this.jButton11 = new JSButton();let jButton11 = this.jButton11;
    this.filler1 = new Filler(new Dimension(0, 30), new Dimension(0, 30), new Dimension(32767, 30));let filler1 = this.filler1;
    this.jButton12 = new JSButton();let jButton12 = this.jButton12;
    this.filler3 = new Filler(new Dimension(0, 50), new Dimension(0, 50), new Dimension(32767, 50));let filler3 = this.filler3;
    this.jPanel5 = new JSPanel();let jPanel5 = this.jPanel5;
    this.jComboBox1 = new JSComboBox();let jComboBox1 = this.jComboBox1;
    this.jComboBox2 = new JSComboBox();let jComboBox2 = this.jComboBox2;
    this.jComboBox3 = new JSComboBox();let jComboBox3 = this.jComboBox3;
    this.jComboBox4 = new JSComboBox();let jComboBox4 = this.jComboBox4;
    this.jSpinner1 = new JSSpinner();let jSpinner1 = this.jSpinner1;
    this.jSpinner2 = new JSSpinner();let jSpinner2 = this.jSpinner2;
    this.jTextField1 = new JSTextField();let jTextField1 = this.jTextField1;
    this.jTextField2 = new JSTextField();let jTextField2 = this.jTextField2;
    this.jTextField3 = new JSTextField();let jTextField3 = this.jTextField3;
    this.jPanel6 = new JSPanel();let jPanel6 = this.jPanel6;
    this.jPanel4 = new JSPanel();let jPanel4 = this.jPanel4;
    this.jCheckBox1 = new JSCheckBox();let jCheckBox1 = this.jCheckBox1;
    this.jCheckBox2 = new JSCheckBox();let jCheckBox2 = this.jCheckBox2;
    this.jCheckBox3 = new JSCheckBox();let jCheckBox3 = this.jCheckBox3;
    this.jCheckBox4 = new JSCheckBox();let jCheckBox4 = this.jCheckBox4;
    this.jRadioButton1 = new JSRadioButton();let jRadioButton1 = this.jRadioButton1;
    this.jRadioButton2 = new JSRadioButton();let jRadioButton2 = this.jRadioButton2;
    this.jRadioButton3 = new JSRadioButton();let jRadioButton3 = this.jRadioButton3;
    this.jRadioButton4 = new JSRadioButton();let jRadioButton4 = this.jRadioButton4;
    this.jCheckBox5 = new JSCheckBox();let jCheckBox5 = this.jCheckBox5;
    this.jCheckBox6 = new JSCheckBox();let jCheckBox6 = this.jCheckBox6;
    this.jCheckBox7 = new JSCheckBox();let jCheckBox7 = this.jCheckBox7;
    this.jCheckBox8 = new JSCheckBox();let jCheckBox8 = this.jCheckBox8;
    this.jRadioButton21 = new JSRadioButton();let jRadioButton21 = this.jRadioButton21;
    this.jRadioButton22 = new JSRadioButton();let jRadioButton22 = this.jRadioButton22;
    this.jRadioButton23 = new JSRadioButton();let jRadioButton23 = this.jRadioButton23;
    this.jRadioButton24 = new JSRadioButton();let jRadioButton24 = this.jRadioButton24;
    this.jPanel7 = new JSPanel();let jPanel7 = this.jPanel7;
    this.jToggleButton1 = new JSToggleButton();let jToggleButton1 = this.jToggleButton1;
    this.jToggleButton2 = new JSToggleButton();let jToggleButton2 = this.jToggleButton2;
    this.jToggleButton3 = new JSToggleButton();let jToggleButton3 = this.jToggleButton3;
    this.jToggleButton4 = new JSToggleButton();let jToggleButton4 = this.jToggleButton4;
    this.jToggleButton5 = new JSToggleButton();let jToggleButton5 = this.jToggleButton5;
    this.jToggleButton6 = new JSToggleButton();let jToggleButton6 = this.jToggleButton6;
    this.jToggleButton7 = new JSToggleButton();let jToggleButton7 = this.jToggleButton7;
    this.jToggleButton8 = new JSToggleButton();let jToggleButton8 = this.jToggleButton8;
    this.jToggleButton9 = new JSToggleButton();let jToggleButton9 = this.jToggleButton9;
    this.jToggleButton10 = new JSToggleButton();let jToggleButton10 = this.jToggleButton10;
    this.jToggleButton11 = new JSToggleButton();let jToggleButton11 = this.jToggleButton11;
    this.jToggleButton12 = new JSToggleButton();let jToggleButton12 = this.jToggleButton12;
    this.jToggleButton13 = new JSToggleButton();let jToggleButton13 = this.jToggleButton13;
    this.jToggleButton14 = new JSToggleButton();let jToggleButton14 = this.jToggleButton14;
    this.jToggleButton15 = new JSToggleButton();let jToggleButton15 = this.jToggleButton15;
    this.jToggleButton16 = new JSToggleButton();let jToggleButton16 = this.jToggleButton16;
    this.setTitle("Test Components");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton2.setText("jButton2");
    jPanel1.add(jButton2);
    jButton3.setText("jButton3");
    jButton3.setEnabled(false);
    jPanel1.add(jButton3);
    jButton4.setText("jButton1");
    jButton4.setContentAreaFilled(false);
    jButton4.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton4ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton4);
    jButton6.setText("jButton2");
    jButton6.setContentAreaFilled(false);
    jPanel1.add(jButton6);
    jButton7.setText("jButton3");
    jButton7.setContentAreaFilled(false);
    jButton7.setEnabled(false);
    jPanel1.add(jButton7);
    jButton9.setText("jButton1");
    jButton9.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton9ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton9);
    jButton13.setText("jButton3");
    jButton13.setEnabled(false);
    jPanel1.add(jButton13);
    jButton14.setText("jButton1");
    jButton14.setContentAreaFilled(false);
    jButton14.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton14ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton14);
    jButton15.setText("jButton3");
    jButton15.setContentAreaFilled(false);
    jButton15.setEnabled(false);
    jPanel1.add(jButton15);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    jPanel2.setLayout(new GridLayout(2, 9, 10, 20));
    jButton5.setText("jButton5");
    jPanel2.add(jButton5);
    buttonGroup2.add(jRadioButton5);
    jRadioButton5.setText("jRadioButton5");
    jPanel2.add(jRadioButton5);
    buttonGroup2.add(jRadioButton7);
    jRadioButton7.setText("jRadioButton7");
    jRadioButton7.setEnabled(false);
    jPanel2.add(jRadioButton7);
    buttonGroup2.add(jRadioButton9);
    jRadioButton9.setText("jRadioButton9");
    jRadioButton9.setContentAreaFilled(false);
    jPanel2.add(jRadioButton9);
    buttonGroup2.add(jRadioButton10);
    jRadioButton10.setText("jRadioButton10");
    jRadioButton10.setContentAreaFilled(false);
    jRadioButton10.setEnabled(false);
    jPanel2.add(jRadioButton10);
    buttonGroup2.add(jRadioButton13);
    jRadioButton13.setText("jRadioButton5");
    jPanel2.add(jRadioButton13);
    buttonGroup2.add(jRadioButton14);
    jRadioButton14.setText("jRadioButton7");
    jRadioButton14.setEnabled(false);
    jPanel2.add(jRadioButton14);
    buttonGroup2.add(jRadioButton15);
    jRadioButton15.setText("jRadioButton9");
    jRadioButton15.setContentAreaFilled(false);
    jPanel2.add(jRadioButton15);
    buttonGroup2.add(jRadioButton16);
    jRadioButton16.setSelected(true);
    jRadioButton16.setText("jRadioButton10");
    jRadioButton16.setContentAreaFilled(false);
    jRadioButton16.setEnabled(false);
    jPanel2.add(jRadioButton16);
    jButton8.setText("jButton8");
    jPanel2.add(jButton8);
    buttonGroup2.add(jRadioButton6);
    jRadioButton6.setText("jRadioButton6");
    jPanel2.add(jRadioButton6);
    buttonGroup2.add(jRadioButton8);
    jRadioButton8.setText("jRadioButton8");
    jRadioButton8.setEnabled(false);
    jPanel2.add(jRadioButton8);
    buttonGroup2.add(jRadioButton11);
    jRadioButton11.setText("jRadioButton11");
    jRadioButton11.setContentAreaFilled(false);
    jPanel2.add(jRadioButton11);
    buttonGroup2.add(jRadioButton12);
    jRadioButton12.setText("jRadioButton12");
    jRadioButton12.setContentAreaFilled(false);
    jRadioButton12.setEnabled(false);
    jPanel2.add(jRadioButton12);
    buttonGroup2.add(jRadioButton17);
    jRadioButton17.setText("jRadioButton6");
    jPanel2.add(jRadioButton17);
    buttonGroup2.add(jRadioButton18);
    jRadioButton18.setText("jRadioButton8");
    jRadioButton18.setEnabled(false);
    jPanel2.add(jRadioButton18);
    buttonGroup2.add(jRadioButton19);
    jRadioButton19.setText("jRadioButton11");
    jRadioButton19.setContentAreaFilled(false);
    jPanel2.add(jRadioButton19);
    buttonGroup2.add(jRadioButton20);
    jRadioButton20.setText("jRadioButton12");
    jRadioButton20.setContentAreaFilled(false);
    jRadioButton20.setEnabled(false);
    jPanel2.add(jRadioButton20);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
    jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));
    jButton10.setText("jButton10");
    jPanel3.add(jButton10);
    jPanel3.add(filler2);
    jButton11.setText("jButton11");
    jPanel3.add(jButton11);
    jPanel3.add(filler1);
    jButton12.setText("jButton12");
    jPanel3.add(jButton12);
    jPanel3.add(filler3);
    this.getContentPane().add(jPanel3, BorderLayout.LINE_START);
    jPanel5.add(jComboBox1);
    jComboBox2.setEnabled(false);
    jPanel5.add(jComboBox2);
    jPanel5.add(jComboBox3);
    jComboBox4.setEnabled(false);
    jPanel5.add(jComboBox4);
    jPanel5.add(jSpinner1);
    jSpinner2.setEnabled(false);
    jPanel5.add(jSpinner2);
    jTextField1.setText("jTextField1");
    jTextField1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jTextField1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel5.add(jTextField1);
    jTextField2.setText("jTextField2");
    jTextField2.setEnabled(false);
    jPanel5.add(jTextField2);
    jTextField3.setEditable(false);
    jTextField3.setText("jTextField3");
    jPanel5.add(jTextField3);
    this.getContentPane().add(jPanel5, BorderLayout.CENTER);
    jPanel6.setLayout(new GridLayout(1, 2, 10, 0));
    jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
    jCheckBox1.setText("jCheckBox1");
    jPanel4.add(jCheckBox1);
    jCheckBox2.setText("jCheckBox2");
    jCheckBox2.setEnabled(false);
    jPanel4.add(jCheckBox2);
    jCheckBox3.setSelected(true);
    jCheckBox3.setText("jCheckBox3");
    jPanel4.add(jCheckBox3);
    jCheckBox4.setSelected(true);
    jCheckBox4.setText("jCheckBox4");
    jCheckBox4.setEnabled(false);
    jPanel4.add(jCheckBox4);
    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("jRadioButton1");
    jPanel4.add(jRadioButton1);
    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("jRadioButton2");
    jRadioButton2.setEnabled(false);
    jPanel4.add(jRadioButton2);
    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setText("jRadioButton3");
    jPanel4.add(jRadioButton3);
    buttonGroup1.add(jRadioButton4);
    jRadioButton4.setText("jRadioButton4");
    jRadioButton4.setEnabled(false);
    jPanel4.add(jRadioButton4);
    jCheckBox5.setText("jCheckBox1");
    jPanel4.add(jCheckBox5);
    jCheckBox6.setText("jCheckBox2");
    jCheckBox6.setEnabled(false);
    jPanel4.add(jCheckBox6);
    jCheckBox7.setSelected(true);
    jCheckBox7.setText("jCheckBox3");
    jPanel4.add(jCheckBox7);
    jCheckBox8.setSelected(true);
    jCheckBox8.setText("jCheckBox4");
    jCheckBox8.setEnabled(false);
    jPanel4.add(jCheckBox8);
    buttonGroup1.add(jRadioButton21);
    jRadioButton21.setText("jRadioButton1");
    jPanel4.add(jRadioButton21);
    buttonGroup1.add(jRadioButton22);
    jRadioButton22.setText("jRadioButton2");
    jRadioButton22.setEnabled(false);
    jPanel4.add(jRadioButton22);
    buttonGroup1.add(jRadioButton23);
    jRadioButton23.setText("jRadioButton3");
    jPanel4.add(jRadioButton23);
    buttonGroup1.add(jRadioButton24);
    jRadioButton24.setSelected(true);
    jRadioButton24.setText("jRadioButton4");
    jRadioButton24.setEnabled(false);
    jPanel4.add(jRadioButton24);
    jPanel6.add(jPanel4);
    jPanel7.setLayout(new BoxLayout(jPanel7, BoxLayout.Y_AXIS));
    jToggleButton1.setText("jToggleButton1");
    jPanel7.add(jToggleButton1);
    jToggleButton2.setText("jToggleButton2");
    jToggleButton2.setEnabled(false);
    jPanel7.add(jToggleButton2);
    jToggleButton3.setSelected(true);
    jToggleButton3.setText("jToggleButton3");
    jPanel7.add(jToggleButton3);
    jToggleButton4.setSelected(true);
    jToggleButton4.setText("jToggleButton4");
    jToggleButton4.setEnabled(false);
    jPanel7.add(jToggleButton4);
    jToggleButton5.setText("jToggleButton1");
    jToggleButton5.setContentAreaFilled(false);
    jPanel7.add(jToggleButton5);
    jToggleButton6.setText("jToggleButton2");
    jToggleButton6.setContentAreaFilled(false);
    jToggleButton6.setEnabled(false);
    jPanel7.add(jToggleButton6);
    jToggleButton7.setSelected(true);
    jToggleButton7.setText("jToggleButton3");
    jToggleButton7.setContentAreaFilled(false);
    jPanel7.add(jToggleButton7);
    jToggleButton8.setSelected(true);
    jToggleButton8.setText("jToggleButton4");
    jToggleButton8.setContentAreaFilled(false);
    jToggleButton8.setEnabled(false);
    jPanel7.add(jToggleButton8);
    jToggleButton9.setText("jToggleButton1");
    jPanel7.add(jToggleButton9);
    jToggleButton10.setText("jToggleButton2");
    jToggleButton10.setEnabled(false);
    jPanel7.add(jToggleButton10);
    jToggleButton11.setSelected(true);
    jToggleButton11.setText("jToggleButton3");
    jPanel7.add(jToggleButton11);
    jToggleButton12.setSelected(true);
    jToggleButton12.setText("jToggleButton4");
    jToggleButton12.setEnabled(false);
    jPanel7.add(jToggleButton12);
    jToggleButton13.setText("jToggleButton1");
    jToggleButton13.setContentAreaFilled(false);
    jPanel7.add(jToggleButton13);
    jToggleButton14.setText("jToggleButton2");
    jToggleButton14.setContentAreaFilled(false);
    jToggleButton14.setEnabled(false);
    jPanel7.add(jToggleButton14);
    jToggleButton15.setSelected(true);
    jToggleButton15.setText("jToggleButton3");
    jToggleButton15.setContentAreaFilled(false);
    jPanel7.add(jToggleButton15);
    jToggleButton16.setSelected(true);
    jToggleButton16.setText("jToggleButton4");
    jToggleButton16.setContentAreaFilled(false);
    jToggleButton16.setEnabled(false);
    jPanel7.add(jToggleButton16);
    jPanel6.add(jPanel7);
    this.getContentPane().add(jPanel6, BorderLayout.LINE_END);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("OK!!!");
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton4ActionPerformed(evt) {
    // GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
  }

  // GEN-LAST:event_jButton4ActionPerformed
   jButton9ActionPerformed(evt) {
    // GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
  }

  // GEN-LAST:event_jButton9ActionPerformed
   jButton14ActionPerformed(evt) {
    // GEN-FIRST:event_jButton14ActionPerformed
    // TODO add your handling code here:
  }

  // GEN-LAST:event_jButton14ActionPerformed
   jTextField1ActionPerformed(evt) {
    // GEN-FIRST:event_jTextField1ActionPerformed
    this.jTextField2.setText(this.jTextField1.getText());
  }

  // GEN-LAST:event_jTextField1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
   buttonGroup1 = null;

   buttonGroup2 = null;

   filler1 = null;

   filler2 = null;

   filler3 = null;

   jButton1 = null;

   jButton10 = null;

   jButton11 = null;

   jButton12 = null;

   jButton13 = null;

   jButton14 = null;

   jButton15 = null;

   jButton2 = null;

   jButton3 = null;

   jButton4 = null;

   jButton5 = null;

   jButton6 = null;

   jButton7 = null;

   jButton8 = null;

   jButton9 = null;

   jCheckBox1 = null;

   jCheckBox2 = null;

   jCheckBox3 = null;

   jCheckBox4 = null;

   jCheckBox5 = null;

   jCheckBox6 = null;

   jCheckBox7 = null;

   jCheckBox8 = null;

   jComboBox1 = null;

   jComboBox2 = null;

   jComboBox3 = null;

   jComboBox4 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jPanel5 = null;

   jPanel6 = null;

   jPanel7 = null;

   jRadioButton1 = null;

   jRadioButton10 = null;

   jRadioButton11 = null;

   jRadioButton12 = null;

   jRadioButton13 = null;

   jRadioButton14 = null;

   jRadioButton15 = null;

   jRadioButton16 = null;

   jRadioButton17 = null;

   jRadioButton18 = null;

   jRadioButton19 = null;

   jRadioButton2 = null;

   jRadioButton20 = null;

   jRadioButton21 = null;

   jRadioButton22 = null;

   jRadioButton23 = null;

   jRadioButton24 = null;

   jRadioButton3 = null;

   jRadioButton4 = null;

   jRadioButton5 = null;

   jRadioButton6 = null;

   jRadioButton7 = null;

   jRadioButton8 = null;

   jRadioButton9 = null;

   jSpinner1 = null;

   jSpinner2 = null;

   jTextField1 = null;

   jTextField2 = null;

   jTextField3 = null;

   jToggleButton1 = null;

   jToggleButton10 = null;

   jToggleButton11 = null;

   jToggleButton12 = null;

   jToggleButton13 = null;

   jToggleButton14 = null;

   jToggleButton15 = null;

   jToggleButton16 = null;

   jToggleButton2 = null;

   jToggleButton3 = null;

   jToggleButton4 = null;

   jToggleButton5 = null;

   jToggleButton6 = null;

   jToggleButton7 = null;

   jToggleButton8 = null;

   jToggleButton9 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame2HTMLImageProducer extends DefaultHTMLImageProducer {

  constructor(value, src) {
    super(value, src);
  }

   produce() {
    let img = super.produce();
    img.width = 20;
    img.height = 20;
    return img;
  }
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame3 extends JSFrame {

   modelAndRendererS = null;

   modelAndRendererS2 = null;

   modelAndRendererS3 = null;

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    this.modelAndRendererS = new DefaultSliderModelAndRenderer();
    this.modelAndRendererS.addElement("A");
    this.modelAndRendererS.addElement("B");
    this.modelAndRendererS.addElement("C");
    (SwingJS.convert(this.jSlider5)).setModelAndRenderer(this.modelAndRendererS);
    this.modelAndRendererS2 = new HTMLImageSliderModelAndRenderer();
    this.modelAndRendererS2.addElement(new TestJSFrame3HTMLImageProducer("A", "../../../swing.png"));
    this.modelAndRendererS2.addElement(new TestJSFrame3HTMLImageProducer("B", "../../../swing.png"));
    this.modelAndRendererS2.addElement(new TestJSFrame3HTMLImageProducer("C", "../../../swing.png"));
    this.modelAndRendererS2.addElement(new TestJSFrame3HTMLImageProducer("D", "../../../swing.png"));
    (SwingJS.convert(this.jSlider6)).setModelAndRenderer(this.modelAndRendererS2);
    this.modelAndRendererS3 = new HTMLImageSliderModelAndRenderer();
    this.modelAndRendererS3.addElement(new TestJSFrame3HTMLImageProducer("A", "../../../swing.png"));
    this.modelAndRendererS3.addElement(new TestJSFrame3HTMLImageProducer("B", "../../../swing.png"));
    this.modelAndRendererS3.addElement(new TestJSFrame3HTMLImageProducer("C", "../../../swing.png"));
    this.modelAndRendererS3.addElement(new TestJSFrame3HTMLImageProducer("D", "../../../swing.png"));
    (SwingJS.convert(this.jSlider7)).setModelAndRenderer(this.modelAndRendererS3);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    let gridBagConstraints = null;
    this.jSlider1 = new JSSlider();let jSlider1 = this.jSlider1;
    this.jSlider2 = new JSSlider();let jSlider2 = this.jSlider2;
    this.jSlider3 = new JSSlider();let jSlider3 = this.jSlider3;
    this.jSlider4 = new JSSlider();let jSlider4 = this.jSlider4;
    this.jSlider5 = new JSSlider();let jSlider5 = this.jSlider5;
    this.jSlider6 = new JSSlider();let jSlider6 = this.jSlider6;
    this.jSlider7 = new JSSlider();let jSlider7 = this.jSlider7;
    this.jLabel1 = new JSLabel();let jLabel1 = this.jLabel1;
    this.setTitle("Test Slider");
    let layout = new GridBagLayout();
    layout.columnWidths = [0, 30, 0, 30, 0, 30, 0, ];
    layout.rowHeights = [0, 5, 0, 5, 0, 5, 0, 5, 0, ];
    this.getContentPane().setLayout(layout);
    jSlider1.setMajorTickSpacing(50);
    jSlider1.setMaximum(300);
    jSlider1.setMinimum(100);
    jSlider1.setOrientation(JSSlider.VERTICAL);
    jSlider1.setPaintLabels(true);
    jSlider1.setPaintTicks(true);
    jSlider1.setValue(230);
    jSlider1.setInverted(true);
    jSlider1.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider1StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridheight = 7;
    gridBagConstraints.fill = GridBagConstraints.VERTICAL;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider1, gridBagConstraints);
    jSlider2.setMajorTickSpacing(50);
    jSlider2.setMaximum(300);
    jSlider2.setMinimum(100);
    jSlider2.setPaintLabels(true);
    jSlider2.setPaintTicks(true);
    jSlider2.setValue(230);
    jSlider2.setEnabled(false);
    jSlider2.setInverted(true);
    jSlider2.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider2StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider2, gridBagConstraints);
    jSlider3.setMajorTickSpacing(50);
    jSlider3.setMaximum(300);
    jSlider3.setMinimum(100);
    jSlider3.setPaintLabels(true);
    jSlider3.setPaintTicks(true);
    jSlider3.setValue(230);
    jSlider3.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider3StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider3, gridBagConstraints);
    jSlider4.setMajorTickSpacing(50);
    jSlider4.setMaximum(300);
    jSlider4.setMinimum(100);
    jSlider4.setOrientation(JSSlider.VERTICAL);
    jSlider4.setPaintLabels(true);
    jSlider4.setPaintTicks(true);
    jSlider4.setPaintTrack(false);
    jSlider4.setValue(230);
    jSlider4.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider4StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridheight = 7;
    gridBagConstraints.fill = GridBagConstraints.VERTICAL;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider4, gridBagConstraints);
    jSlider5.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider5StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider5, gridBagConstraints);
    jSlider6.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider6StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider6, gridBagConstraints);
    jSlider7.setOrientation(JSSlider.VERTICAL);
    jSlider7.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider7StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 9;
    gridBagConstraints.fill = GridBagConstraints.VERTICAL;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jSlider7, gridBagConstraints);
    jLabel1.setText("jLabel1");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 7;
    this.getContentPane().add(jLabel1, gridBagConstraints);
  }

  // </editor-fold>//GEN-END:initComponents
   jSlider1StateChanged(evt) {
    // GEN-FIRST:event_jSlider1StateChanged
    this.jLabel1.setText(this.jSlider1.getValueIsAdjusting() + " " + this.jSlider1.getValue());
  }

  // GEN-LAST:event_jSlider1StateChanged
   jSlider2StateChanged(evt) {
    // GEN-FIRST:event_jSlider2StateChanged
    this.jLabel1.setText(this.jSlider2.getValueIsAdjusting() + " " + this.jSlider2.getValue());
  }

  // GEN-LAST:event_jSlider2StateChanged
   jSlider3StateChanged(evt) {
    // GEN-FIRST:event_jSlider3StateChanged
    this.jLabel1.setText(this.jSlider3.getValueIsAdjusting() + " " + this.jSlider3.getValue());
  }

  // GEN-LAST:event_jSlider3StateChanged
   jSlider4StateChanged(evt) {
    // GEN-FIRST:event_jSlider4StateChanged
    this.jLabel1.setText(this.jSlider4.getValueIsAdjusting() + " " + this.jSlider4.getValue());
  }

  // GEN-LAST:event_jSlider4StateChanged
   jSlider5StateChanged(evt) {
    // GEN-FIRST:event_jSlider5StateChanged
    this.jLabel1.setText(this.jSlider5.getValueIsAdjusting() + " " + this.modelAndRendererS.getElementAt(this.jSlider5.getValue()));
  }

  // GEN-LAST:event_jSlider5StateChanged
   jSlider6StateChanged(evt) {
    // GEN-FIRST:event_jSlider6StateChanged
    this.jLabel1.setText(this.jSlider6.getValueIsAdjusting() + " " + this.modelAndRendererS2.getElementAt(this.jSlider6.getValue()).getValue());
  }

  // GEN-LAST:event_jSlider6StateChanged
   jSlider7StateChanged(evt) {
    // GEN-FIRST:event_jSlider7StateChanged
    this.jLabel1.setText(this.jSlider7.getValueIsAdjusting() + " " + this.modelAndRendererS3.getElementAt(this.jSlider7.getValue()).getValue());
  }

  // GEN-LAST:event_jSlider7StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jLabel1 = null;

   jSlider1 = null;

   jSlider2 = null;

   jSlider3 = null;

   jSlider4 = null;

   jSlider5 = null;

   jSlider6 = null;

   jSlider7 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame3HTMLImageProducer extends DefaultHTMLImageProducer {

  constructor(value, src) {
    super(value, src);
  }

   produce() {
    let img = super.produce();
    switch(this.getValue()) {
      case "A":
        break;
      case "B":
        img.style.transform = "rotate(15deg) scale(0.8)";
        break;
      case "C":
        img.style.filter = "drop-shadow(2px 4px 6px black)";
        break;
      case "D":
        break;
    }
    return img;
  }
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame4 extends JSFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel4 = new JSPanel();let jPanel4 = this.jPanel4;
    this.jProgressBar2 = new JSProgressBar();let jProgressBar2 = this.jProgressBar2;
    this.jProgressBar1 = new JSProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jProgressBar4 = new JSProgressBar();let jProgressBar4 = this.jProgressBar4;
    this.jProgressBar6 = new JSProgressBar();let jProgressBar6 = this.jProgressBar6;
    this.jPanel5 = new JSPanel();let jPanel5 = this.jPanel5;
    this.jProgressBar3 = new JSProgressBar();let jProgressBar3 = this.jProgressBar3;
    this.jProgressBar5 = new JSProgressBar();let jProgressBar5 = this.jProgressBar5;
    this.setTitle("Test Progress");
    jPanel4.setLayout(new GridLayout(4, 1, 0, 5));
    jProgressBar2.setIndeterminate(true);
    jPanel4.add(jProgressBar2);
    jProgressBar1.setMaximum(1000);
    jProgressBar1.setMinimum(30);
    jProgressBar1.setValue(570);
    jPanel4.add(jProgressBar1);
    jProgressBar4.setMaximum(1000);
    jProgressBar4.setMinimum(30);
    jProgressBar4.setValue(570);
    jProgressBar4.setStringPainted(true);
    jPanel4.add(jProgressBar4);
    jProgressBar6.setValue(49);
    jProgressBar6.setString("Frase di Test");
    jProgressBar6.setStringPainted(true);
    jPanel4.add(jProgressBar6);
    this.getContentPane().add(jPanel4, BorderLayout.PAGE_END);
    jPanel5.setLayout(new GridLayout(1, 2, 5, 0));
    jProgressBar3.setOrientation(1);
    jProgressBar3.setValue(30);
    jPanel5.add(jProgressBar3);
    jProgressBar5.setOrientation(1);
    jProgressBar5.setValue(30);
    jProgressBar5.setStringPainted(true);
    jPanel5.add(jProgressBar5);
    this.getContentPane().add(jPanel5, BorderLayout.LINE_END);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jPanel4 = null;

   jPanel5 = null;

   jProgressBar1 = null;

   jProgressBar2 = null;

   jProgressBar3 = null;

   jProgressBar4 = null;

   jProgressBar5 = null;

   jProgressBar6 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame5 extends JSFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jTabbedPane2)).setAlign(JSTabbedPane.CENTER);
    (SwingJS.convert(this.jTabbedPane3)).setAlign(JSTabbedPane.END);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    let gridBagConstraints = null;
    this.jTabbedPane1 = new JSTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.jTabbedPane2 = new JSTabbedPane();let jTabbedPane2 = this.jTabbedPane2;
    this.jPanel3 = new JSPanel();let jPanel3 = this.jPanel3;
    this.jPanel4 = new JSPanel();let jPanel4 = this.jPanel4;
    this.jTabbedPane3 = new JSTabbedPane();let jTabbedPane3 = this.jTabbedPane3;
    this.jPanel5 = new JSPanel();let jPanel5 = this.jPanel5;
    this.jPanel6 = new JSPanel();let jPanel6 = this.jPanel6;
    this.jTabbedPane4 = new JSTabbedPane();let jTabbedPane4 = this.jTabbedPane4;
    this.jPanel7 = new JSPanel();let jPanel7 = this.jPanel7;
    this.jPanel8 = new JSPanel();let jPanel8 = this.jPanel8;
    this.setTitle("Test Tabs");
    this.getContentPane().setLayout(new GridBagLayout());
    jTabbedPane1.setTabPlacement(JSTabbedPane.LEFT);
    jPanel1.setBackground(new Color(0, 255, 255));
    jTabbedPane1.addTab("tab1", jPanel1);
    jPanel2.setBackground(new Color(0, 0, 255));
    jTabbedPane1.addTab("tab2", jPanel2);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane1, gridBagConstraints);
    jTabbedPane2.setTabPlacement(JSTabbedPane.RIGHT);
    jPanel3.setBackground(new Color(0, 255, 0));
    jTabbedPane2.addTab("tab1", jPanel3);
    jPanel4.setBackground(new Color(0, 0, 204));
    jTabbedPane2.addTab("tab2", jPanel4);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane2, gridBagConstraints);
    jPanel5.setBackground(new Color(255, 255, 0));
    jTabbedPane3.addTab("tab1", jPanel5);
    jPanel6.setBackground(new Color(255, 51, 51));
    jTabbedPane3.addTab("tab2", jPanel6);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane3, gridBagConstraints);
    jTabbedPane4.setTabPlacement(JSTabbedPane.BOTTOM);
    jPanel7.setBackground(new Color(153, 0, 153));
    jTabbedPane4.addTab("tab1", jPanel7);
    jPanel8.setBackground(new Color(255, 204, 204));
    jTabbedPane4.addTab("tab2", jPanel8);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane4, gridBagConstraints);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jPanel5 = null;

   jPanel6 = null;

   jPanel7 = null;

   jPanel8 = null;

   jTabbedPane1 = null;

   jTabbedPane2 = null;

   jTabbedPane3 = null;

   jTabbedPane4 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame6 extends JSFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jDialog1)).addWindowClosedListener(event => console.log("WINDOW CLOSED!!!"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jDialog1 = new JSDialog();let jDialog1 = this.jDialog1;
    this.jButton3 = new JSButton();let jButton3 = this.jButton3;
    this.jButton4 = new JSButton();let jButton4 = this.jButton4;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.jButton2 = new JSButton();let jButton2 = this.jButton2;
    this.jToggleButton1 = new JSToggleButton();let jToggleButton1 = this.jToggleButton1;
    this.jCheckBox1 = new JSCheckBox();let jCheckBox1 = this.jCheckBox1;
    this.jSpinner1 = new JSSpinner();let jSpinner1 = this.jSpinner1;
    this.jRadioButton1 = new JSRadioButton();let jRadioButton1 = this.jRadioButton1;
    this.jSlider1 = new JSSlider();let jSlider1 = this.jSlider1;
    this.jRadioButton2 = new JSRadioButton();let jRadioButton2 = this.jRadioButton2;
    this.jButton5 = new JSButton();let jButton5 = this.jButton5;
    this.jToggleButton2 = new JSToggleButton();let jToggleButton2 = this.jToggleButton2;
    this.jProgressBar1 = new JSProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jLabel1 = new JSLabel();let jLabel1 = this.jLabel1;
    this.jRadioButton3 = new JSRadioButton();let jRadioButton3 = this.jRadioButton3;
    this.jLabel2 = new JSLabel();let jLabel2 = this.jLabel2;
    this.jRadioButton4 = new JSRadioButton();let jRadioButton4 = this.jRadioButton4;
    this.jButton6 = new JSButton();let jButton6 = this.jButton6;
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jPanel9 = new JSPanel();let jPanel9 = this.jPanel9;
    this.jButton1 = new JSButton();let jButton1 = this.jButton1;
    this.jButton7 = new JSButton();let jButton7 = this.jButton7;
    this.jButton8 = new JSButton();let jButton8 = this.jButton8;
    this.jButton9 = new JSButton();let jButton9 = this.jButton9;
    this.jButton10 = new JSButton();let jButton10 = this.jButton10;
    this.jButton11 = new JSButton();let jButton11 = this.jButton11;
    this.jPanel3 = new JSPanel();let jPanel3 = this.jPanel3;
    this.jButton12 = new JSButton();let jButton12 = this.jButton12;
    this.jButton13 = new JSButton();let jButton13 = this.jButton13;
    this.jButton14 = new JSButton();let jButton14 = this.jButton14;
    this.jButton15 = new JSButton();let jButton15 = this.jButton15;
    this.jButton16 = new JSButton();let jButton16 = this.jButton16;
    jDialog1.setTitle("Dialog");
    jDialog1.getContentPane().setLayout(new GridLayout(1, 2));
    jButton3.setText("jButton3");
    jDialog1.getContentPane().add(jButton3);
    jButton4.setText("close");
    jButton4.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton4ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jDialog1.getContentPane().add(jButton4);
    this.setTitle("Test Dialog");
    jPanel2.setLayout(new GridLayout(5, 5));
    jButton2.setText("jButton2");
    jPanel2.add(jButton2);
    jToggleButton1.setText("jToggleButton1");
    jPanel2.add(jToggleButton1);
    jCheckBox1.setText("jCheckBox1");
    jPanel2.add(jCheckBox1);
    jPanel2.add(jSpinner1);
    jRadioButton1.setText("jRadioButton1");
    jPanel2.add(jRadioButton1);
    jPanel2.add(jSlider1);
    jRadioButton2.setText("jRadioButton2");
    jPanel2.add(jRadioButton2);
    jButton5.setText("jButton5");
    jPanel2.add(jButton5);
    jToggleButton2.setText("jToggleButton2");
    jPanel2.add(jToggleButton2);
    jPanel2.add(jProgressBar1);
    jLabel1.setText("jLabel1");
    jPanel2.add(jLabel1);
    jRadioButton3.setText("jRadioButton3");
    jPanel2.add(jRadioButton3);
    jLabel2.setText("jLabel2");
    jPanel2.add(jLabel2);
    jRadioButton4.setText("jRadioButton4");
    jPanel2.add(jRadioButton4);
    jButton6.setText("jButton6");
    jPanel2.add(jButton6);
    this.getContentPane().add(jPanel2, BorderLayout.CENTER);
    jPanel1.setLayout(new GridLayout(2, 1));
    jPanel9.setBackground(new Color(255, 255, 102));
    jButton1.setText("modal");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton1);
    jButton7.setText("message error");
    jButton7.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton7ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton7);
    jButton8.setText("message question");
    jButton8.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton8ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton8);
    jButton9.setText("message info");
    jButton9.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton9ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton9);
    jButton10.setText("message warning");
    jButton10.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton10ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton10);
    jButton11.setText("message info with component");
    jButton11.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton11ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel9.add(jButton11);
    jPanel1.add(jPanel9);
    jPanel3.setBackground(new Color(102, 255, 102));
    jButton12.setText("confirm error");
    jButton12.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton12ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton12);
    jButton13.setText("confirm question");
    jButton13.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton13ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton13);
    jButton14.setText("confirm info");
    jButton14.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton14ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton14);
    jButton15.setText("confirm warning");
    jButton15.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton15ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton15);
    jButton16.setText("confirm info with component");
    jButton16.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton16ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton16);
    jPanel1.add(jPanel3);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    this.jDialog1.setVisible(true);
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton4ActionPerformed(evt) {
    // GEN-FIRST:event_jButton4ActionPerformed
    this.jDialog1.setVisible(false);
  }

  // GEN-LAST:event_jButton4ActionPerformed
   jButton7ActionPerformed(evt) {
    // GEN-FIRST:event_jButton7ActionPerformed
    JSOptionPane.showMessageDialog("Hello World", "Title", JSOptionPane.ERROR_MESSAGE, null);
  }

  // GEN-LAST:event_jButton7ActionPerformed
   jButton8ActionPerformed(evt) {
    // GEN-FIRST:event_jButton8ActionPerformed
    JSOptionPane.showMessageDialog("Hello World", "Title", JSOptionPane.QUESTION_MESSAGE, null);
  }

  // GEN-LAST:event_jButton8ActionPerformed
   jButton9ActionPerformed(evt) {
    // GEN-FIRST:event_jButton9ActionPerformed
    JSOptionPane.showMessageDialog("Hello World", "Title", JSOptionPane.INFORMATION_MESSAGE, () => console.log("closed"));
  }

  // GEN-LAST:event_jButton9ActionPerformed
   jButton10ActionPerformed(evt) {
    // GEN-FIRST:event_jButton10ActionPerformed
    JSOptionPane.showMessageDialog("Hello World", "Title", JSOptionPane.WARNING_MESSAGE, () => console.log("closed"));
  }

  // GEN-LAST:event_jButton10ActionPerformed
   jButton11ActionPerformed(evt) {
    // GEN-FIRST:event_jButton11ActionPerformed
    let panel = new JSPanel();
    let label = new JSLabel();
    label.setText("Hello");
    label.setBackground(new Color(255, 0, 0));
    panel.add(label);
    label = new JSLabel();
    label.setText("World");
    label.setBackground(new Color(255, 255, 0));
    panel.add(label);
    JSOptionPane.showMessageDialog(panel, "Title", JSOptionPane.INFORMATION_MESSAGE, () => console.log("closed"));
  }

  // GEN-LAST:event_jButton11ActionPerformed
   jButton12ActionPerformed(evt) {
    // GEN-FIRST:event_jButton12ActionPerformed
    JSOptionPane.showConfirmDialog("Hello World", "Title", JSOptionPane.YES_NO_OPTION, JSOptionPane.ERROR_MESSAGE, value => console.log(value));
  }

  // GEN-LAST:event_jButton12ActionPerformed
   jButton13ActionPerformed(evt) {
    // GEN-FIRST:event_jButton13ActionPerformed
    JSOptionPane.showConfirmDialog("Hello World", "Title", JSOptionPane.YES_NO_OPTION, JSOptionPane.QUESTION_MESSAGE, value => console.log(value));
  }

  // GEN-LAST:event_jButton13ActionPerformed
   jButton14ActionPerformed(evt) {
    // GEN-FIRST:event_jButton14ActionPerformed
    JSOptionPane.showConfirmDialog("Hello World", "Title", JSOptionPane.YES_NO_CANCEL_OPTION, JSOptionPane.INFORMATION_MESSAGE, value => console.log(value));
  }

  // GEN-LAST:event_jButton14ActionPerformed
   jButton15ActionPerformed(evt) {
    // GEN-FIRST:event_jButton15ActionPerformed
    JSOptionPane.showConfirmDialog("Hello World", "Title", JSOptionPane.OK_CANCEL_OPTION, JSOptionPane.WARNING_MESSAGE, value => console.log(value));
  }

  // GEN-LAST:event_jButton15ActionPerformed
   jButton16ActionPerformed(evt) {
    // GEN-FIRST:event_jButton16ActionPerformed
    let panel = new JSPanel();
    let label = new JSLabel();
    label.setText("Hello");
    label.setBackground(new Color(255, 0, 0));
    panel.add(label);
    label = new JSLabel();
    label.setText("World");
    label.setBackground(new Color(255, 255, 0));
    panel.add(label);
    JSOptionPane.showConfirmDialog(panel, "Title", JSOptionPane.OK_CANCEL_OPTION, JSOptionPane.WARNING_MESSAGE, value => console.log(value));
  }

  // GEN-LAST:event_jButton16ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jButton1 = null;

   jButton10 = null;

   jButton11 = null;

   jButton12 = null;

   jButton13 = null;

   jButton14 = null;

   jButton15 = null;

   jButton16 = null;

   jButton2 = null;

   jButton3 = null;

   jButton4 = null;

   jButton5 = null;

   jButton6 = null;

   jButton7 = null;

   jButton8 = null;

   jButton9 = null;

   jCheckBox1 = null;

   jDialog1 = null;

   jLabel1 = null;

   jLabel2 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel9 = null;

   jProgressBar1 = null;

   jRadioButton1 = null;

   jRadioButton2 = null;

   jRadioButton3 = null;

   jRadioButton4 = null;

   jSlider1 = null;

   jSpinner1 = null;

   jToggleButton1 = null;

   jToggleButton2 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame7 extends JSFrame {

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jRadioButton9)).setToggle();
    (SwingJS.convert(this.jRadioButton15)).setToggle();
    let modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox1)).setModelAndRenderer(modelAndRendererCB);
    (SwingJS.convert(this.jSpinner1)).setModel(new SpinnerNumberModel(10, 5, 50, 1));
    (SwingJS.convert(this.jButton9)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton9)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton15)).setIcon(new TestJSFrame2HTMLImageProducer("", "../../../swing.png"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.buttonGroup2 = new ButtonGroup();let buttonGroup2 = this.buttonGroup2;
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JSButton();let jButton1 = this.jButton1;
    this.jButton9 = new JSButton();let jButton9 = this.jButton9;
    this.jComboBox1 = new JSComboBox();let jComboBox1 = this.jComboBox1;
    this.jSpinner1 = new JSSpinner();let jSpinner1 = this.jSpinner1;
    this.jTextField1 = new JSTextField();let jTextField1 = this.jTextField1;
    this.jToggleButton1 = new JSToggleButton();let jToggleButton1 = this.jToggleButton1;
    this.jToggleButton9 = new JSToggleButton();let jToggleButton9 = this.jToggleButton9;
    this.jRadioButton9 = new JSRadioButton();let jRadioButton9 = this.jRadioButton9;
    this.jRadioButton15 = new JSRadioButton();let jRadioButton15 = this.jRadioButton15;
    this.jProgressBar1 = new JSProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jTabbedPane1 = new JSTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.jPanel3 = new JSPanel();let jPanel3 = this.jPanel3;
    this.jPanel4 = new JSPanel();let jPanel4 = this.jPanel4;
    this.jLabel1 = new JSLabel();let jLabel1 = this.jLabel1;
    this.jSlider1 = new JSSlider();let jSlider1 = this.jSlider1;
    this.setTitle("Test Roundness");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton9.setText("jButton1");
    jButton9.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton9ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton9);
    jPanel1.add(jComboBox1);
    jPanel1.add(jSpinner1);
    jTextField1.setText("jTextField1");
    jTextField1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jTextField1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jTextField1);
    jToggleButton1.setText("jToggleButton1");
    jPanel1.add(jToggleButton1);
    jToggleButton9.setText("jToggleButton1");
    jPanel1.add(jToggleButton9);
    buttonGroup2.add(jRadioButton9);
    jRadioButton9.setText("jRadioButton9");
    jRadioButton9.setContentAreaFilled(false);
    jPanel1.add(jRadioButton9);
    buttonGroup2.add(jRadioButton15);
    jRadioButton15.setText("jRadioButton9");
    jRadioButton15.setContentAreaFilled(false);
    jPanel1.add(jRadioButton15);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_END);
    jProgressBar1.setOrientation(1);
    jProgressBar1.setValue(35);
    jProgressBar1.setStringPainted(true);
    this.getContentPane().add(jProgressBar1, BorderLayout.LINE_END);
    jTabbedPane1.addTab("tab1 hello", jPanel2);
    jTabbedPane1.addTab("tab2", jPanel3);
    this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
    jPanel4.setLayout(new BorderLayout());
    jLabel1.setText("0.5");
    jPanel4.add(jLabel1, BorderLayout.CENTER);
    jSlider1.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider1StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel4.add(jSlider1, BorderLayout.SOUTH);
    this.getContentPane().add(jPanel4, BorderLayout.NORTH);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("OK!!!");
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton9ActionPerformed(evt) {
    // GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
  }

  // GEN-LAST:event_jButton9ActionPerformed
   jTextField1ActionPerformed(evt) {
    // GEN-FIRST:event_jTextField1ActionPerformed
  }

  // GEN-LAST:event_jTextField1ActionPerformed
   jSlider1StateChanged(evt) {
    // GEN-FIRST:event_jSlider1StateChanged
    let v = this.jSlider1.getValue() / 100.0;
    this.jLabel1.setText("" + v);
    document.head.removeChild(document.head.querySelector("style"));
    SwingJS.instance().roundness(v).build();
  }

  // GEN-LAST:event_jSlider1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
   buttonGroup2 = null;

   jButton1 = null;

   jButton9 = null;

   jComboBox1 = null;

   jLabel1 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jProgressBar1 = null;

   jRadioButton15 = null;

   jRadioButton9 = null;

   jSlider1 = null;

   jSpinner1 = null;

   jTabbedPane1 = null;

   jTextField1 = null;

   jToggleButton1 = null;

   jToggleButton9 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame8 extends JSFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JSButton();let jButton1 = this.jButton1;
    this.jButton2 = new JSButton();let jButton2 = this.jButton2;
    this.jButton3 = new JSButton();let jButton3 = this.jButton3;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.setTitle("Test File Chooser");
    jButton1.setText("Open Single File");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton2.setText("Open Multiple Files");
    jButton2.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton2ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton2);
    jButton3.setText("Open Files in Folder");
    jButton3.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton3ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton3);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    this.getContentPane().add(jPanel2, BorderLayout.CENTER);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    this.open(JSFileChooser.SINGLE_SELECTION);
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton2ActionPerformed(evt) {
    // GEN-FIRST:event_jButton2ActionPerformed
    this.open(JSFileChooser.MULTIPLE_SELECTION);
  }

  // GEN-LAST:event_jButton2ActionPerformed
   jButton3ActionPerformed(evt) {
    // GEN-FIRST:event_jButton3ActionPerformed
    this.open(JSFileChooser.FOLDER_SELECTION);
  }

  // GEN-LAST:event_jButton3ActionPerformed
   open(selectionType) {
    JSFileChooser.showOpenDialog(".gif,.png,.jpeg,.jpg", selectionType, 0, files => {
      document.querySelectorAll("img").forEach(img => img.parentElement.removeChild(img));
      files.forEach(file => {
        let fileReader = new FileReader();
        fileReader.onload = event => {
          let img = document.createElement("img");
          img.src = fileReader.result;
          document.querySelector(".center").appendChild(img);
          return null;
        };
        fileReader.readAsDataURL(file);
      });
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
   jButton1 = null;

   jButton2 = null;

   jButton3 = null;

   jPanel1 = null;

   jPanel2 = null;
  // End of variables declaration//GEN-END:variables
}
/**
 * @author gianpiero.diblasi
 */
class TestJSFrame9 extends JSFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    let swatchesPanel = new JSColorSwatchesPanel();
    swatchesPanel.addActionListener(event => console.log(swatchesPanel.getSelectedColor().getRGB_HEX()));
    (SwingJS.convert(this.jPanel2)).add(swatchesPanel, null);
    let hsvPanel = new JSColorHSVPanel();
    hsvPanel.addChangeListener(event => console.log(hsvPanel.getSelectedColor().getRGB_HEX()));
    swatchesPanel.addActionListener(event => hsvPanel.setSelectedColor(swatchesPanel.getSelectedColor()));
    (SwingJS.convert(this.jPanel2)).add(hsvPanel, null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JSPanel();let jPanel1 = this.jPanel1;
    this.jButton4 = new JSButton();let jButton4 = this.jButton4;
    this.jButton5 = new JSButton();let jButton5 = this.jButton5;
    this.jPanel2 = new JSPanel();let jPanel2 = this.jPanel2;
    this.setTitle("Test Color Chooser");
    jButton4.setText("Choose Color");
    jButton4.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton4ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton4);
    jButton5.setText("Choose Color With Default");
    jButton5.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton5ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton5);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    this.getContentPane().add(jPanel2, BorderLayout.CENTER);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton4ActionPerformed(evt) {
    // GEN-FIRST:event_jButton4ActionPerformed
    // this.choose(null);
  }

  // GEN-LAST:event_jButton4ActionPerformed
   jButton5ActionPerformed(evt) {
    // GEN-FIRST:event_jButton5ActionPerformed
    // this.choose(new Color(255, 0, 0,255));
  }

  // GEN-LAST:event_jButton5ActionPerformed
  // private void open(int selectionType) {
  // JSFileChooser.showOpenDialog(".gif,.png,.jpeg,.jpg", selectionType, 0, files -> {
  // document.querySelectorAll("img").forEach(img -> img.parentElement.removeChild(img));
  // 
  // files.forEach(file -> {
  // FileReader fileReader = new FileReader();
  // fileReader.onload = event -> {
  // $Image img = ($Image) document.createElement("img");
  // img.src = (String) fileReader.result;
  // 
  // document.querySelector(".center").appendChild(img);
  // return null;
  // };
  // fileReader.readAsDataURL(file);
  // });
  // });
  // }
  // private void choose(Color color) {
  // JSColorChooser.showDialog(color, c -> {
  // document.querySelectorAll("img").forEach(img -> img.parentElement.removeChild(img));
  // $Image img = ($Image) document.createElement("img");
  // img.width = 100;
  // img.height = 100;
  // img.style.background = c.getRGB_HEX();
  // document.querySelector(".center").appendChild(img);
  // });
  // }
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jButton4 = null;

   jButton5 = null;

   jPanel1 = null;

   jPanel2 = null;
  // End of variables declaration//GEN-END:variables
}
