package javascript.swing;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author gianpiero.diblasi
 */
@SuppressWarnings("serial")
public class TestJFrame5 extends javax.swing.JFrame {

  /**
   * Creates new form TestFrame3
   */
  public TestJFrame5() {
    super();
    this.initComponents();
    this.postInitComponents();
  }
  
  private void postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDialog1 = new JDialog();
    jButton3 = new JButton();
    jButton4 = new JButton();
    jPanel9 = new JPanel();
    jButton1 = new JButton();

    jDialog1.setTitle("Dialogo");
    jDialog1.getContentPane().setLayout(new GridLayout(1, 2));

    jButton3.setText("jButton3");
    jDialog1.getContentPane().add(jButton3);

    jButton4.setText("close");
    jButton4.addActionListener(this::jButton4ActionPerformed);
    jDialog1.getContentPane().add(jButton4);

    setTitle("TestJFrame5");

    jButton1.setText("modal");
    jButton1.addActionListener(this::jButton1ActionPerformed);
    jPanel9.add(jButton1);

    getContentPane().add(jPanel9, BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.jDialog1.setVisible(true);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.jDialog1.setVisible(false);
  }//GEN-LAST:event_jButton4ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton jButton1;
  private JButton jButton3;
  private JButton jButton4;
  private JDialog jDialog1;
  private JPanel jPanel9;
  // End of variables declaration//GEN-END:variables
}
