package javascript.swing;

import static def.dom.Globals.console;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import javascript.SwingJS;
import javascript.swing.colorchooser.JSColorCMYKPanel;
import javascript.swing.colorchooser.JSColorHSLPanel;
import javascript.swing.colorchooser.JSColorHSVPanel;
import javascript.swing.colorchooser.JSColorMiniSwatchesPanel;
import javascript.swing.colorchooser.JSColorRGBPanel;
import javascript.swing.colorchooser.JSColorSwatchesPanel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author gianpiero.diblasi
 */
@SuppressWarnings("serial")
public class TestJFrame10 extends javax.swing.JFrame {

  /**
   * Creates new form TestFrame3
   */
  public TestJFrame10() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

  private void postInitComponents() {
//    JSColorMiniSwatchesPanel miniSwatchesPanel = new JSColorMiniSwatchesPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(miniSwatchesPanel, null);
//
//    JSColorSwatchesPanel swatchesPanel = new JSColorSwatchesPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(swatchesPanel, null);
//
//    JSColorHSVPanel hsvPanel = new JSColorHSVPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(hsvPanel, null);
//
//    JSColorHSLPanel hslPanel = new JSColorHSLPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(hslPanel, null);
//
//    JSColorRGBPanel rgbPanel = new JSColorRGBPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(rgbPanel, null);
//
//    JSColorCMYKPanel cmykPanel = new JSColorCMYKPanel();
//    ((JSPanel) SwingJS.convert(this.jPanel2)).add(cmykPanel, null);
//
//    miniSwatchesPanel.addActionListener(event -> {
//      console.log(miniSwatchesPanel.getSelectedColor().getRGB_HEX());
//
//      hsvPanel.setSelectedColor(miniSwatchesPanel.getSelectedColor());
//      hslPanel.setSelectedColor(miniSwatchesPanel.getSelectedColor());
//      rgbPanel.setSelectedColor(miniSwatchesPanel.getSelectedColor());
//      cmykPanel.setSelectedColor(miniSwatchesPanel.getSelectedColor());
//    });
//
//    swatchesPanel.addActionListener(event -> {
//      console.log(swatchesPanel.getSelectedColor().getRGB_HEX());
//
//      hsvPanel.setSelectedColor(swatchesPanel.getSelectedColor());
//      hslPanel.setSelectedColor(swatchesPanel.getSelectedColor());
//      rgbPanel.setSelectedColor(swatchesPanel.getSelectedColor());
//      cmykPanel.setSelectedColor(swatchesPanel.getSelectedColor());
//    });
//
//    hsvPanel.addChangeListener(event -> {
//      if (this.jCheckBox1.isSelected() || !hsvPanel.getValueIsAdjusting()) {
//        console.log(hsvPanel.getSelectedColor().getRGB_HEX());
//
//        hslPanel.setSelectedColor(hsvPanel.getSelectedColor());
//        rgbPanel.setSelectedColor(hsvPanel.getSelectedColor());
//        cmykPanel.setSelectedColor(hsvPanel.getSelectedColor());
//      }
//    });
//
//    hslPanel.addChangeListener(event -> {
//      if (this.jCheckBox1.isSelected() || !hslPanel.getValueIsAdjusting()) {
//        console.log(hslPanel.getSelectedColor().getRGB_HEX());
//
//        hsvPanel.setSelectedColor(hslPanel.getSelectedColor());
//        rgbPanel.setSelectedColor(hslPanel.getSelectedColor());
//        cmykPanel.setSelectedColor(hslPanel.getSelectedColor());
//      }
//    });
//
//    rgbPanel.addChangeListener(event -> {
//      if (this.jCheckBox1.isSelected() || !rgbPanel.getValueIsAdjusting()) {
//        console.log(rgbPanel.getSelectedColor().getRGB_HEX());
//
//        hsvPanel.setSelectedColor(rgbPanel.getSelectedColor());
//        hslPanel.setSelectedColor(rgbPanel.getSelectedColor());
//        cmykPanel.setSelectedColor(rgbPanel.getSelectedColor());
//      }
//    });
//
//    cmykPanel.addChangeListener(event -> {
//      if (this.jCheckBox1.isSelected() || !cmykPanel.getValueIsAdjusting()) {
//        console.log(cmykPanel.getSelectedColor().getRGB_HEX());
//
//        hsvPanel.setSelectedColor(cmykPanel.getSelectedColor());
//        hslPanel.setSelectedColor(cmykPanel.getSelectedColor());
//        rgbPanel.setSelectedColor(cmykPanel.getSelectedColor());
//      }
//    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new JPanel();
    jButton4 = new JButton();
    jButton5 = new JButton();
    jPanel2 = new JPanel();

    setTitle("Test Color Chooser");

    jButton4.setText("Choose Color");
    jButton4.addActionListener(this::jButton4ActionPerformed);
    jPanel1.add(jButton4);

    jButton5.setText("Choose Color With Default");
    jButton5.addActionListener(this::jButton5ActionPerformed);
    jPanel1.add(jButton5);

    getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    getContentPane().add(jPanel2, BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//    this.choose(null);
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//    this.choose(new Color(255, 0, 0,255));
  }//GEN-LAST:event_jButton5ActionPerformed

//  private void open(int selectionType) {
//    JSFileChooser.showOpenDialog(".gif,.png,.jpeg,.jpg", selectionType, 0, files -> {
//      document.querySelectorAll("img").forEach(img -> img.parentElement.removeChild(img));
//
//      files.forEach(file -> {
//        FileReader fileReader = new FileReader();
//        fileReader.onload = event -> {
//          $Image img = ($Image) document.createElement("img");
//          img.src = (String) fileReader.result;
//
//          document.querySelector(".center").appendChild(img);
//          return null;
//        };
//        fileReader.readAsDataURL(file);
//      });
//    });
//  }
//  private void choose(Color color) {
//    JSColorChooser.showDialog(color, c -> {
//      document.querySelectorAll("img").forEach(img -> img.parentElement.removeChild(img));
//      $Image img = ($Image) document.createElement("img");
//      img.width = 100;
//      img.height = 100;
//      img.style.background = c.getRGB_HEX();
//      document.querySelector(".center").appendChild(img);
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton jButton4;
  private JButton jButton5;
  private JPanel jPanel1;
  private JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
