package javascript.swing;

import java.awt.BorderLayout;
import javax.swing.JTabbedPane;

/**
 *
 * @author gianpiero.diblasi
 */
public class TestJFrame4 extends javax.swing.JFrame {

  private static final long serialVersionUID = 1;

  /**
   * Creates new form TestFrame3
   */
  public TestJFrame4() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

  @SuppressWarnings("unchecked")
  private void postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new JTabbedPane();

    getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JTabbedPane jTabbedPane1;
  // End of variables declaration//GEN-END:variables
}
