package giada.swing;

import java.awt.GridBagLayout;

/**
 *
 * @author gianpiero.diblasi
 */
public class TestJFrame2 extends javax.swing.JFrame {

  private static final long serialVersionUID = 1;

  public TestJFrame2() {
    super();
    this.initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setTitle("Test JFrame1");
    getContentPane().setLayout(new GridBagLayout());
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
