package giada.swing;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author gianpiero.diblasi
 */
public class TestJFrame2 extends javax.swing.JFrame {

  private static final long serialVersionUID = 1;

  public TestJFrame2() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

  private void postInitComponents() {
    AbstractComboBoxModelAndRenderer<Integer> modelAndRenderer = new DefaultComboBoxModelAndRenderer<>();
    modelAndRenderer.addElement(10);
    modelAndRenderer.addElement(20);
    modelAndRenderer.addElement(30);
    
    this.jComboBox2.putClientProperty("model-and-renderer", modelAndRenderer);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    GridBagConstraints gridBagConstraints;

    buttonGroup1 = new ButtonGroup();
    jLabel1 = new JLabel();
    jLabel2 = new JLabel();
    jComboBox1 = new JComboBox<>();
    jComboBox2 = new JComboBox<>();
    jCheckBox1 = new JCheckBox();
    jCheckBox2 = new JCheckBox();
    jButton1 = new JButton();
    jRadioButton1 = new JRadioButton();
    jRadioButton2 = new JRadioButton();

    setTitle("Test JFrame2");
    GridBagLayout layout = new GridBagLayout();
    layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0};
    layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
    getContentPane().setLayout(layout);

    jLabel1.setText("Face:");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    getContentPane().add(jLabel1, gridBagConstraints);

    jLabel2.setText("Size:");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = GridBagConstraints.EAST;
    getContentPane().add(jLabel2, gridBagConstraints);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 100.0;
    gridBagConstraints.insets = new Insets(5, 5, 5, 5);
    getContentPane().add(jComboBox1, gridBagConstraints);

    jComboBox2.addActionListener(this::jComboBox2ActionPerformed);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 10;
    gridBagConstraints.ipady = 10;
    gridBagConstraints.weightx = 100.0;
    getContentPane().add(jComboBox2, gridBagConstraints);

    jCheckBox1.setSelected(true);
    jCheckBox1.setText("Bold");
    jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.weightx = 100.0;
    gridBagConstraints.weighty = 100.0;
    getContentPane().add(jCheckBox1, gridBagConstraints);

    jCheckBox2.setText("Italic");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.weightx = 100.0;
    gridBagConstraints.weighty = 100.0;
    getContentPane().add(jCheckBox2, gridBagConstraints);

    jButton1.setText("jButton1");
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 7;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 100.0;
    gridBagConstraints.weighty = 100.0;
    getContentPane().add(jButton1, gridBagConstraints);

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("pomodoro");
    jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    getContentPane().add(jRadioButton1, gridBagConstraints);

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("patate");
    jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 10;
    getContentPane().add(jRadioButton2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    this.jCheckBox2.setSelected(this.jCheckBox1.isSelected());
  }//GEN-LAST:event_jCheckBox1ActionPerformed

  private void jComboBox2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    this.jButton1.setText(this.jComboBox2.getSelectedItem().toString());
  }//GEN-LAST:event_jComboBox2ActionPerformed

  private void jRadioButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    this.jButton1.setText(this.jRadioButton1.getText());
  }//GEN-LAST:event_jRadioButton1ActionPerformed

  private void jRadioButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    this.jButton1.setText(this.jRadioButton2.getText());
  }//GEN-LAST:event_jRadioButton2ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ButtonGroup buttonGroup1;
  private JButton jButton1;
  private JCheckBox jCheckBox1;
  private JCheckBox jCheckBox2;
  private JComboBox<String> jComboBox1;
  private JComboBox<Integer> jComboBox2;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JRadioButton jRadioButton1;
  private JRadioButton jRadioButton2;
  // End of variables declaration//GEN-END:variables
}
