/**
 * @author gianpiero.diblasi
 */
class TestJFrame1 extends JFrame {

  static  serialVersionUID = 1;

  constructor() {
    super();
    this.initComponents();
    let jPanel2 = new JPanel();
    let jButton2 = new JButton();
    jButton2.setText("jButton2");
    jButton2.addActionListener(new TestJFrame1ActionListener());
    jPanel2.add(jButton2);
    this.getContentPane().add(jPanel2, BorderLayout.SOUTH);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    let jPanel1 = new JPanel();
    let jButton1 = new JButton();
    let jButton5 = new JButton();
    let jPanel2 = new JPanel();
    let jButton2 = new JButton();
    let jPanel3 = new JPanel();
    let jButton3 = new JButton();
    let jPanel4 = new JPanel();
    let jButton4 = new JButton();
    let jPanel5 = new JPanel();
    this.setTitle("Test JFrame1");
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton5.setText("jButton5");
    jPanel1.add(jButton5);
    this.getContentPane().add(jPanel1, BorderLayout.NORTH);
    jButton2.setText("jButton2");
    jPanel2.add(jButton2);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
    jButton3.setText("jButton3");
    jPanel3.add(jButton3);
    this.getContentPane().add(jPanel3, BorderLayout.LINE_END);
    jButton4.setText("jButton4");
    jPanel4.add(jButton4);
    this.getContentPane().add(jPanel4, BorderLayout.LINE_START);
    this.getContentPane().add(jPanel5, BorderLayout.CENTER);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("FROM LAMBDA");
  }
  // GEN-LAST:event_jButton1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
