package giada.swingjs;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author gianpiero.diblasi
 */
public class TestJFrame1 extends javax.swing.JFrame {

  private static final long serialVersionUID = 1;

  public TestJFrame1() {
    super();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JPanel jPanel1 = new javax.swing.JPanel();

    setTitle("Test JFrame1");
    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
