package giada.swingjs;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author gianpiero.diblasi
 */
public class TestJFrame1 extends javax.swing.JFrame {

  private static final long serialVersionUID = 1;

  public TestJFrame1() {
    super();
    this.initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new JPanel();

    getContentPane().add(jPanel1, BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
