/**
 * @author gianpiero.diblasi
 */
class TestJFrame2 extends JFrame {

  static  serialVersionUID = 1;

  constructor() {
    super();
    this.initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.setTitle("Test JFrame1");
    this.getContentPane().setLayout(new GridBagLayout());
  }
  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
