/**
 * @author gianpiero.diblasi
 */
class TestJFrame1 extends JFrame {

  static  serialVersionUID = 1;

  constructor() {
    super();
    this.initComponents();
    let jPanel22 = new JPanel();
    let jButton22 = new JButton();
    jButton22.setText("jButton2");
    jButton22.addActionListener(new TestJFrame1ActionListener());
    jPanel22.add(jButton22);
    jPanel22.setBackground(new Color(200, 100, 200));
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    this.getContentPane().add(jPanel22, BorderLayout.CENTER);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JButton();let jButton1 = this.jButton1;
    this.jButton5 = new JButton();let jButton5 = this.jButton5;
    this.jButton6 = new JButton();let jButton6 = this.jButton6;
    this.jButton7 = new JButton();let jButton7 = this.jButton7;
    this.jButton8 = new JButton();let jButton8 = this.jButton8;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jButton2 = new JButton();let jButton2 = this.jButton2;
    this.jButton9 = new JButton();let jButton9 = this.jButton9;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jButton3 = new JButton();let jButton3 = this.jButton3;
    this.jButton10 = new JButton();let jButton10 = this.jButton10;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jButton4 = new JButton();let jButton4 = this.jButton4;
    this.setTitle("Test JFrame1");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jPanel1.setBackground(new Color(255, 255, 0));
    jPanel1.setLayout(new GridLayout(2, 3, 5, 5));
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton5.setText("jButton5");
    jPanel1.add(jButton5);
    jButton6.setText("jButton6");
    jPanel1.add(jButton6);
    jButton7.setText("jButton7");
    jPanel1.add(jButton7);
    jButton8.setText("jButton8");
    jPanel1.add(jButton8);
    this.getContentPane().add(jPanel1, BorderLayout.NORTH);
    jPanel2.setBackground(new Color(0, 102, 102));
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.LINE_AXIS));
    jButton2.setText("jButton2");
    jPanel2.add(jButton2);
    jButton9.setText("jButton9");
    jPanel2.add(jButton9);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
    jPanel3.setBackground(new Color(153, 255, 153));
    jPanel3.setLayout(new CardLayout());
    jButton3.setText("jButton3");
    jPanel3.add(jButton3, "card2");
    jButton10.setText("jButton10");
    jPanel3.add(jButton10, "card3");
    this.getContentPane().add(jPanel3, BorderLayout.LINE_END);
    jPanel4.setBackground(new Color(0, 51, 0));
    jButton4.setText("jButton4");
    jPanel4.add(jButton4);
    this.getContentPane().add(jPanel4, BorderLayout.LINE_START);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("FROM LAMBDA");
  }

  // GEN-LAST:event_jButton1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jButton1 = null;

   jButton10 = null;

   jButton2 = null;

   jButton3 = null;

   jButton4 = null;

   jButton5 = null;

   jButton6 = null;

   jButton7 = null;

   jButton8 = null;

   jButton9 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;
  // End of variables declaration//GEN-END:variables
}
