/**
 * @author gianpiero.diblasi
 */
class TestJFrame1 extends javax.swing.JFrame {

  static  serialVersionUID = 1;

  constructor() {
    super();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
  }
  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
