/**
 * @author gianpiero.diblasi
 */
class TestJFrame1 extends JFrame {

  static  serialVersionUID = 1;

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    let jPanel22 = new JPanel();
    let jButton22 = new JButton();
    jButton22.setText("jButton2");
    jButton22.addActionListener(new TestJFrame1ActionListener());
    jPanel22.add(jButton22);
    jPanel22.setBackground(new Color(200, 100, 200));
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    jPanel22.add(new JButton());
    this.getContentPane().add(jPanel22, BorderLayout.CENTER);
    this.jPanel2.add(new JButton());
    this.jLabel1.setText(LookAndFeel.CURRENT.getDescription());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JButton();let jButton1 = this.jButton1;
    this.jButton5 = new JButton();let jButton5 = this.jButton5;
    this.jButton6 = new JButton();let jButton6 = this.jButton6;
    this.jButton7 = new JButton();let jButton7 = this.jButton7;
    this.jSpinner1 = new JSpinner();let jSpinner1 = this.jSpinner1;
    this.jLabel1 = new JLabel();let jLabel1 = this.jLabel1;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jButton2 = new JButton();let jButton2 = this.jButton2;
    this.filler1 = new Filler(new Dimension(10, 0), new Dimension(10, 0), new Dimension(10, 32767));let filler1 = this.filler1;
    this.jButton9 = new JButton();let jButton9 = this.jButton9;
    this.filler4 = new Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));let filler4 = this.filler4;
    this.jSpinner2 = new JSpinner();let jSpinner2 = this.jSpinner2;
    this.jButton11 = new JButton();let jButton11 = this.jButton11;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jButton3 = new JButton();let jButton3 = this.jButton3;
    this.jButton10 = new JButton();let jButton10 = this.jButton10;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jButton4 = new JButton();let jButton4 = this.jButton4;
    this.filler2 = new Filler(new Dimension(0, 20), new Dimension(0, 20), new Dimension(32767, 20));let filler2 = this.filler2;
    this.jButton12 = new JButton();let jButton12 = this.jButton12;
    this.filler3 = new Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));let filler3 = this.filler3;
    this.jButton13 = new JButton();let jButton13 = this.jButton13;
    this.filler5 = new Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 32767));let filler5 = this.filler5;
    this.setTitle("Test JFrame1");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jPanel1.setBackground(new Color(255, 255, 0));
    jPanel1.setLayout(new GridLayout(2, 3, 20, 5));
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton5.setText("jButton5");
    jPanel1.add(jButton5);
    jButton6.setText("jButton6");
    jPanel1.add(jButton6);
    jButton7.setText("jButton7");
    jPanel1.add(jButton7);
    jSpinner1.setModel(new SpinnerNumberModel(6, 2, 10, 2));
    jSpinner1.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSpinner1StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jSpinner1);
    jLabel1.setText("jLabel1");
    jPanel1.add(jLabel1);
    this.getContentPane().add(jPanel1, BorderLayout.NORTH);
    jPanel2.setBackground(new Color(0, 102, 102));
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.LINE_AXIS));
    jButton2.setText("jButton2");
    jPanel2.add(jButton2);
    jPanel2.add(filler1);
    jButton9.setText("jButton9");
    jPanel2.add(jButton9);
    jPanel2.add(filler4);
    jPanel2.add(jSpinner2);
    jButton11.setText("jButton11");
    jPanel2.add(jButton11);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
    jPanel3.setBackground(new Color(153, 255, 153));
    jPanel3.setLayout(new CardLayout(5, 5));
    jButton3.setText("jButton3");
    jButton3.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton3ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton3, "card2");
    jButton10.setText("jButton10");
    jButton10.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton10ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel3.add(jButton10, "card3");
    this.getContentPane().add(jPanel3, BorderLayout.LINE_END);
    jPanel4.setBackground(new Color(0, 51, 0));
    jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.PAGE_AXIS));
    jButton4.setText("jButton4");
    jPanel4.add(jButton4);
    jPanel4.add(filler2);
    jButton12.setText("jButton12");
    jPanel4.add(jButton12);
    jPanel4.add(filler3);
    jButton13.setText("jButton13");
    jPanel4.add(jButton13);
    jPanel4.add(filler5);
    this.getContentPane().add(jPanel4, BorderLayout.LINE_START);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("FROM LAMBDA");
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton3ActionPerformed(evt) {
    // GEN-FIRST:event_jButton3ActionPerformed
    (this.jPanel3.getLayout()).show(this.jPanel3, "card3");
  }

  // GEN-LAST:event_jButton3ActionPerformed
   jButton10ActionPerformed(evt) {
    // GEN-FIRST:event_jButton10ActionPerformed
    (this.jPanel3.getLayout()).show(this.jPanel3, "card2");
  }

  // GEN-LAST:event_jButton10ActionPerformed
   jSpinner1StateChanged(evt) {
    // GEN-FIRST:event_jSpinner1StateChanged
    this.jButton1.setText("" + this.jSpinner1.getValue());
  }

  // GEN-LAST:event_jSpinner1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
   filler1 = null;

   filler2 = null;

   filler3 = null;

   filler4 = null;

   filler5 = null;

   jButton1 = null;

   jButton10 = null;

   jButton11 = null;

   jButton12 = null;

   jButton13 = null;

   jButton2 = null;

   jButton3 = null;

   jButton4 = null;

   jButton5 = null;

   jButton6 = null;

   jButton7 = null;

   jButton9 = null;

   jLabel1 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jSpinner1 = null;

   jSpinner2 = null;
  // End of variables declaration//GEN-END:variables
}
