/**
 * @author gianpiero.diblasi
 */
class TestJFrame3__ extends JFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jCheckBox2)).setSwitch();
    (SwingJS.convert(this.jCheckBox3)).setToggle();
    (SwingJS.convert(this.jRadioButton2)).setSwitch();
    (SwingJS.convert(this.jRadioButton3)).setToggle();
    let modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox1)).setModelAndRenderer(modelAndRendererCB);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.buttonGroup1 = new ButtonGroup();let buttonGroup1 = this.buttonGroup1;
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jCheckBox1 = new JCheckBox();let jCheckBox1 = this.jCheckBox1;
    this.jCheckBox2 = new JCheckBox();let jCheckBox2 = this.jCheckBox2;
    this.jCheckBox3 = new JCheckBox();let jCheckBox3 = this.jCheckBox3;
    this.jCheckBox4 = new JCheckBox();let jCheckBox4 = this.jCheckBox4;
    this.jToggleButton1 = new JToggleButton();let jToggleButton1 = this.jToggleButton1;
    this.jToggleButton2 = new JToggleButton();let jToggleButton2 = this.jToggleButton2;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jRadioButton1 = new JRadioButton();let jRadioButton1 = this.jRadioButton1;
    this.jRadioButton2 = new JRadioButton();let jRadioButton2 = this.jRadioButton2;
    this.jRadioButton3 = new JRadioButton();let jRadioButton3 = this.jRadioButton3;
    this.jComboBox1 = new JComboBox();let jComboBox1 = this.jComboBox1;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jLabel1 = new JLabel();let jLabel1 = this.jLabel1;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jProgressBar2 = new JProgressBar();let jProgressBar2 = this.jProgressBar2;
    this.jProgressBar1 = new JProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jProgressBar4 = new JProgressBar();let jProgressBar4 = this.jProgressBar4;
    this.jProgressBar6 = new JProgressBar();let jProgressBar6 = this.jProgressBar6;
    this.jPanel5 = new JPanel();let jPanel5 = this.jPanel5;
    this.jProgressBar3 = new JProgressBar();let jProgressBar3 = this.jProgressBar3;
    this.jProgressBar5 = new JProgressBar();let jProgressBar5 = this.jProgressBar5;
    this.setTitle("TestJFrame3");
    jCheckBox1.setText("jCheckBox1");
    jCheckBox1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jCheckBox1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jCheckBox1);
    jCheckBox2.setText("jCheckBox2");
    jCheckBox2.setEnabled(false);
    jPanel1.add(jCheckBox2);
    jCheckBox3.setText("jCheckBox3");
    jCheckBox3.setEnabled(false);
    jCheckBox3.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jCheckBox3ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jCheckBox3);
    jCheckBox4.setText("jCheckBox4");
    jPanel1.add(jCheckBox4);
    jToggleButton1.setText("jToggleButton1");
    jToggleButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jToggleButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jToggleButton1);
    jToggleButton2.setText("jToggleButton2");
    jPanel1.add(jToggleButton2);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("jRadioButton1");
    jPanel2.add(jRadioButton1);
    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("jRadioButton2");
    jRadioButton2.setEnabled(false);
    jPanel2.add(jRadioButton2);
    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setText("jRadioButton3");
    jRadioButton3.setEnabled(false);
    jPanel2.add(jRadioButton3);
    jComboBox1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jComboBox1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel2.add(jComboBox1);
    this.getContentPane().add(jPanel2, BorderLayout.CENTER);
    jLabel1.setText("jLabel1");
    jPanel3.add(jLabel1);
    this.getContentPane().add(jPanel3, BorderLayout.LINE_START);
    jPanel4.setLayout(new GridLayout(4, 1));
    jProgressBar2.setIndeterminate(true);
    jPanel4.add(jProgressBar2);
    jProgressBar1.setMaximum(1000);
    jProgressBar1.setMinimum(30);
    jProgressBar1.setValue(570);
    jPanel4.add(jProgressBar1);
    jProgressBar4.setMaximum(1000);
    jProgressBar4.setMinimum(30);
    jProgressBar4.setValue(570);
    jProgressBar4.setStringPainted(true);
    jPanel4.add(jProgressBar4);
    jProgressBar6.setValue(49);
    jProgressBar6.setString("Frase di Test");
    jProgressBar6.setStringPainted(true);
    jPanel4.add(jProgressBar6);
    this.getContentPane().add(jPanel4, BorderLayout.PAGE_END);
    jPanel5.setLayout(new GridLayout(1, 2));
    jProgressBar3.setOrientation(1);
    jProgressBar3.setValue(30);
    jPanel5.add(jProgressBar3);
    jProgressBar5.setOrientation(1);
    jProgressBar5.setValue(30);
    jProgressBar5.setStringPainted(true);
    jPanel5.add(jProgressBar5);
    this.getContentPane().add(jPanel5, BorderLayout.LINE_END);
  }

  // </editor-fold>//GEN-END:initComponents
   jCheckBox1ActionPerformed(evt) {
    // GEN-FIRST:event_jCheckBox1ActionPerformed
    this.jCheckBox2.setSelected(this.jCheckBox1.isSelected());
  }

  // GEN-LAST:event_jCheckBox1ActionPerformed
   jCheckBox3ActionPerformed(evt) {
    // GEN-FIRST:event_jCheckBox3ActionPerformed
    this.jCheckBox4.setSelected(this.jCheckBox3.isSelected());
  }

  // GEN-LAST:event_jCheckBox3ActionPerformed
   jToggleButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jToggleButton1ActionPerformed
    this.jToggleButton2.setSelected(this.jToggleButton1.isSelected());
  }

  // GEN-LAST:event_jToggleButton1ActionPerformed
   jComboBox1ActionPerformed(evt) {
    // GEN-FIRST:event_jComboBox1ActionPerformed
    this.jLabel1.setText("" + this.jComboBox1.getSelectedItem());
  }

  // GEN-LAST:event_jComboBox1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
   buttonGroup1 = null;

   jCheckBox1 = null;

   jCheckBox2 = null;

   jCheckBox3 = null;

   jCheckBox4 = null;

   jComboBox1 = null;

   jLabel1 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jPanel5 = null;

   jProgressBar1 = null;

   jProgressBar2 = null;

   jProgressBar3 = null;

   jProgressBar4 = null;

   jProgressBar5 = null;

   jProgressBar6 = null;

   jRadioButton1 = null;

   jRadioButton2 = null;

   jRadioButton3 = null;

   jToggleButton1 = null;

   jToggleButton2 = null;
  // End of variables declaration//GEN-END:variables
}
