/**
 * @author gianpiero.diblasi
 */
class TestJFrame3 extends JFrame {

  static  serialVersionUID = 1;

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jCheckBox3)).setSwitch();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jCheckBox1 = new JCheckBox();let jCheckBox1 = this.jCheckBox1;
    this.jCheckBox2 = new JCheckBox();let jCheckBox2 = this.jCheckBox2;
    this.jCheckBox3 = new JCheckBox();let jCheckBox3 = this.jCheckBox3;
    this.jCheckBox4 = new JCheckBox();let jCheckBox4 = this.jCheckBox4;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jCheckBox5 = new JCheckBox();let jCheckBox5 = this.jCheckBox5;
    this.jCheckBox6 = new JCheckBox();let jCheckBox6 = this.jCheckBox6;
    this.jLabel1 = new JLabel();let jLabel1 = this.jLabel1;
    jCheckBox1.setText("jCheckBox1");
    jCheckBox1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jCheckBox1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jCheckBox1);
    jCheckBox2.setText("jCheckBox2");
    jPanel1.add(jCheckBox2);
    jCheckBox3.setText("jCheckBox3");
    jCheckBox3.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jCheckBox3ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jCheckBox3);
    jCheckBox4.setText("jCheckBox4");
    jPanel1.add(jCheckBox4);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    jCheckBox5.setText("jCheckBox5");
    jCheckBox5.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jCheckBox5ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel2.add(jCheckBox5);
    jCheckBox6.setText("jCheckBox6");
    jPanel2.add(jCheckBox6);
    jLabel1.setText("jLabel1");
    jPanel2.add(jLabel1);
    this.getContentPane().add(jPanel2, BorderLayout.PAGE_END);
  }

  // </editor-fold>//GEN-END:initComponents
   jCheckBox1ActionPerformed(evt) {
    // GEN-FIRST:event_jCheckBox1ActionPerformed
    this.jCheckBox2.setSelected(this.jCheckBox1.isSelected());
  }

  // GEN-LAST:event_jCheckBox1ActionPerformed
   jCheckBox3ActionPerformed(evt) {
    // GEN-FIRST:event_jCheckBox3ActionPerformed
    this.jCheckBox4.setSelected(this.jCheckBox3.isSelected());
  }

  // GEN-LAST:event_jCheckBox3ActionPerformed
   jCheckBox5ActionPerformed(evt) {
    // GEN-FIRST:event_jCheckBox5ActionPerformed
    this.jCheckBox6.setSelected(this.jCheckBox5.isSelected());
  }

  // GEN-LAST:event_jCheckBox5ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jCheckBox1 = null;

   jCheckBox2 = null;

   jCheckBox3 = null;

   jCheckBox4 = null;

   jCheckBox5 = null;

   jCheckBox6 = null;

   jLabel1 = null;

   jPanel1 = null;

   jPanel2 = null;
  // End of variables declaration//GEN-END:variables
}
