/**
 * @author gianpiero.diblasi
 */
class TestJFrame4 extends JFrame {

  static  serialVersionUID = 1;

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jTabbedPane1 = new JTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jTabbedPane1 = null;
  // End of variables declaration//GEN-END:variables
}
