/**
 * @author gianpiero.diblasi
 */
class TestJFrame4 extends JFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jProgressBar2 = new JProgressBar();let jProgressBar2 = this.jProgressBar2;
    this.jProgressBar1 = new JProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jProgressBar4 = new JProgressBar();let jProgressBar4 = this.jProgressBar4;
    this.jProgressBar6 = new JProgressBar();let jProgressBar6 = this.jProgressBar6;
    this.jPanel5 = new JPanel();let jPanel5 = this.jPanel5;
    this.jProgressBar3 = new JProgressBar();let jProgressBar3 = this.jProgressBar3;
    this.jProgressBar5 = new JProgressBar();let jProgressBar5 = this.jProgressBar5;
    this.setTitle("Test Progress");
    jPanel4.setLayout(new GridLayout(4, 1, 0, 5));
    jProgressBar2.setIndeterminate(true);
    jPanel4.add(jProgressBar2);
    jProgressBar1.setMaximum(1000);
    jProgressBar1.setMinimum(30);
    jProgressBar1.setValue(570);
    jPanel4.add(jProgressBar1);
    jProgressBar4.setMaximum(1000);
    jProgressBar4.setMinimum(30);
    jProgressBar4.setValue(570);
    jProgressBar4.setStringPainted(true);
    jPanel4.add(jProgressBar4);
    jProgressBar6.setValue(49);
    jProgressBar6.setString("Frase di Test");
    jProgressBar6.setStringPainted(true);
    jPanel4.add(jProgressBar6);
    this.getContentPane().add(jPanel4, BorderLayout.PAGE_END);
    jPanel5.setLayout(new GridLayout(1, 2, 5, 0));
    jProgressBar3.setOrientation(1);
    jProgressBar3.setValue(30);
    jPanel5.add(jProgressBar3);
    jProgressBar5.setOrientation(1);
    jProgressBar5.setValue(30);
    jProgressBar5.setStringPainted(true);
    jPanel5.add(jProgressBar5);
    this.getContentPane().add(jPanel5, BorderLayout.LINE_END);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jPanel4 = null;

   jPanel5 = null;

   jProgressBar1 = null;

   jProgressBar2 = null;

   jProgressBar3 = null;

   jProgressBar4 = null;

   jProgressBar5 = null;

   jProgressBar6 = null;
  // End of variables declaration//GEN-END:variables
}
