/**
 * @author gianpiero.diblasi
 */
class TestJFrame10 extends JFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    for (let i = 0; i < 100; i++) {
      Color.pushHistory(new Color(parseInt(255 * Math.random()), parseInt(255 * Math.random()), parseInt(255 * Math.random()), parseInt(255 * Math.random())));
    }
    let colorPanel = new JSColorPanel();
    (SwingJS.convert(this.jPanel2)).add(colorPanel, null);
    let colorPanelNoOpacity = new JSColorPanel();
    colorPanelNoOpacity.setOpacityVisible(false);
    colorPanelNoOpacity.addExtraTab("Extra", new JSColorExtraTab1Panel());
    (SwingJS.convert(this.jPanel2)).add(colorPanelNoOpacity, null);
    colorPanel.addChangeListener(event => {
      if (this.jCheckBox1.isSelected() || !colorPanel.getValueIsAdjusting()) {
        console.log(colorPanel.getSelectedColor().getARGB_HEX());
      }
    });
    colorPanelNoOpacity.addChangeListener(event => {
      if (this.jCheckBox1.isSelected() || !colorPanelNoOpacity.getValueIsAdjusting()) {
        console.log(colorPanelNoOpacity.getSelectedColor().getARGB_HEX());
      }
    });
    let chooser = new JSColorChooser();
    (SwingJS.convert(this.jPanel1)).add(chooser, null);
    chooser.addChangeListener(event => {
      if (this.jCheckBox1.isSelected() || !chooser.getValueIsAdjusting()) {
        console.log(chooser.getSelectedColor().getARGB_HEX());
      }
    });
    let chooser2 = new JSColorChooser();
    chooser2.setEnabled(false);
    (SwingJS.convert(this.jPanel1)).add(chooser2, null);
    chooser2 = new JSColorChooser();
    chooser2.setSelectedColor(new Color(255, 0, 0, 255));
    chooser2.setCloseOnChange(false);
    (SwingJS.convert(this.jPanel1)).add(chooser2, null);
    chooser2 = new JSColorChooser();
    chooser2.setEnabled(false);
    chooser2.setSelectedColor(new Color(255, 0, 0, 255));
    (SwingJS.convert(this.jPanel1)).add(chooser2, null);
    chooser2 = new JSColorChooser();
    chooser2.setSelectedColor(new Color(255, 0, 0, 255));
    (SwingJS.convert(this.jPanel3)).add(chooser2, null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jButton4 = new JButton();let jButton4 = this.jButton4;
    this.jButton5 = new JButton();let jButton5 = this.jButton5;
    this.jCheckBox1 = new JCheckBox();let jCheckBox1 = this.jCheckBox1;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.setTitle("Test Color Chooser");
    jButton4.setText("Choose Color");
    jButton4.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton4ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton4);
    jButton5.setText("Choose Color With Default");
    jButton5.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton5ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton5);
    jCheckBox1.setSelected(true);
    jCheckBox1.setText("realtime");
    jPanel1.add(jCheckBox1);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_START);
    this.getContentPane().add(jPanel2, BorderLayout.CENTER);
    jPanel3.setLayout(new FlowLayout(FlowLayout.RIGHT));
    this.getContentPane().add(jPanel3, BorderLayout.PAGE_END);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton4ActionPerformed(evt) {
    // GEN-FIRST:event_jButton4ActionPerformed
    this.choose(null);
  }

  // GEN-LAST:event_jButton4ActionPerformed
   jButton5ActionPerformed(evt) {
    // GEN-FIRST:event_jButton5ActionPerformed
    this.choose(new Color(255, 0, 0, 255));
  }

  // GEN-LAST:event_jButton5ActionPerformed
   choose(color) {
    let array = new Array();
    array["EXTRA"] = new JSColorExtraTab1Panel();
    JSColorChooser.showDialog("Select a color", color, true, array, c => {
      if (c) {
        console.log(c.getRGBA_HEX());
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
   jButton4 = null;

   jButton5 = null;

   jCheckBox1 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;
  // End of variables declaration//GEN-END:variables
}
