/**
 * @author gianpiero.diblasi
 */
class TestJFrame5 extends JFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jTabbedPane2)).setAlign(JSTabbedPane.CENTER);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.jTabbedPane1 = new JTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jTabbedPane2 = new JTabbedPane();let jTabbedPane2 = this.jTabbedPane2;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.getContentPane().setLayout(new GridLayout(1, 2));
    jTabbedPane1.setTabPlacement(JTabbedPane.LEFT);
    jPanel1.setBackground(new Color(255, 255, 0));
    jTabbedPane1.addTab("tab1", jPanel1);
    jPanel2.setBackground(new Color(255, 51, 51));
    jTabbedPane1.addTab("tab2", jPanel2);
    this.getContentPane().add(jTabbedPane1);
    jTabbedPane2.setTabPlacement(JTabbedPane.RIGHT);
    jPanel3.setBackground(new Color(0, 255, 0));
    jTabbedPane2.addTab("tab1", jPanel3);
    jPanel4.setBackground(new Color(0, 0, 204));
    jTabbedPane2.addTab("tab2", jPanel4);
    this.getContentPane().add(jTabbedPane2);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jTabbedPane1 = null;

   jTabbedPane2 = null;
  // End of variables declaration//GEN-END:variables
}
