/**
 * @author gianpiero.diblasi
 */
class TestJFrame4 extends JFrame {

  /**
   * Creates new form TestFrame3
   */
  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jTabbedPane2)).setAlign(JSTabbedPane.CENTER);
    (SwingJS.convert(this.jTabbedPane3)).setAlign(JSTabbedPane.END);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    let gridBagConstraints = null;
    this.jTabbedPane1 = new JTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jTabbedPane2 = new JTabbedPane();let jTabbedPane2 = this.jTabbedPane2;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jTabbedPane3 = new JTabbedPane();let jTabbedPane3 = this.jTabbedPane3;
    this.jPanel5 = new JPanel();let jPanel5 = this.jPanel5;
    this.jPanel6 = new JPanel();let jPanel6 = this.jPanel6;
    this.jTabbedPane4 = new JTabbedPane();let jTabbedPane4 = this.jTabbedPane4;
    this.jPanel7 = new JPanel();let jPanel7 = this.jPanel7;
    this.jPanel8 = new JPanel();let jPanel8 = this.jPanel8;
    this.getContentPane().setLayout(new GridBagLayout());
    jTabbedPane1.setTabPlacement(JTabbedPane.LEFT);
    jPanel1.setBackground(new Color(0, 255, 255));
    jTabbedPane1.addTab("tab1", jPanel1);
    jPanel2.setBackground(new Color(0, 0, 255));
    jTabbedPane1.addTab("tab2", jPanel2);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane1, gridBagConstraints);
    jTabbedPane2.setTabPlacement(JTabbedPane.RIGHT);
    jPanel3.setBackground(new Color(0, 255, 0));
    jTabbedPane2.addTab("tab1", jPanel3);
    jPanel4.setBackground(new Color(0, 0, 204));
    jTabbedPane2.addTab("tab2", jPanel4);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane2, gridBagConstraints);
    jPanel5.setBackground(new Color(255, 255, 0));
    jTabbedPane3.addTab("tab1", jPanel5);
    jPanel6.setBackground(new Color(255, 51, 51));
    jTabbedPane3.addTab("tab2", jPanel6);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane3, gridBagConstraints);
    jTabbedPane4.setTabPlacement(JTabbedPane.BOTTOM);
    jPanel7.setBackground(new Color(153, 0, 153));
    jTabbedPane4.addTab("tab1", jPanel7);
    jPanel8.setBackground(new Color(255, 204, 204));
    jTabbedPane4.addTab("tab2", jPanel8);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    this.getContentPane().add(jTabbedPane4, gridBagConstraints);
  }

  // </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jPanel5 = null;

   jPanel6 = null;

   jPanel7 = null;

   jPanel8 = null;

   jTabbedPane1 = null;

   jTabbedPane2 = null;

   jTabbedPane3 = null;

   jTabbedPane4 = null;
  // End of variables declaration//GEN-END:variables
}
