/**
 * @author gianpiero.diblasi
 */
class TestJFrame7 extends JFrame {

  constructor() {
    super();
    this.initComponents();
    this.postInitComponents();
  }

   postInitComponents() {
    (SwingJS.convert(this.jRadioButton9)).setToggle();
    (SwingJS.convert(this.jRadioButton15)).setToggle();
    let modelAndRendererCB = new DefaultComboBoxModelAndRenderer();
    modelAndRendererCB.addElement(10);
    modelAndRendererCB.addElement(20);
    modelAndRendererCB.addElement(30);
    (SwingJS.convert(this.jComboBox1)).setModelAndRenderer(modelAndRendererCB);
    (SwingJS.convert(this.jSpinner1)).setModel(new SpinnerNumberModel(10, 5, 50, 1));
    (SwingJS.convert(this.jButton9)).setIcon(new TestJFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jToggleButton9)).setIcon(new TestJFrame2HTMLImageProducer("", "../../../swing.png"));
    (SwingJS.convert(this.jRadioButton15)).setIcon(new TestJFrame2HTMLImageProducer("", "../../../swing.png"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   initComponents() {
    this.buttonGroup2 = new ButtonGroup();let buttonGroup2 = this.buttonGroup2;
    this.jPanel1 = new JPanel();let jPanel1 = this.jPanel1;
    this.jButton1 = new JButton();let jButton1 = this.jButton1;
    this.jButton9 = new JButton();let jButton9 = this.jButton9;
    this.jComboBox1 = new JComboBox();let jComboBox1 = this.jComboBox1;
    this.jSpinner1 = new JSpinner();let jSpinner1 = this.jSpinner1;
    this.jTextField1 = new JTextField();let jTextField1 = this.jTextField1;
    this.jToggleButton1 = new JToggleButton();let jToggleButton1 = this.jToggleButton1;
    this.jToggleButton9 = new JToggleButton();let jToggleButton9 = this.jToggleButton9;
    this.jRadioButton9 = new JRadioButton();let jRadioButton9 = this.jRadioButton9;
    this.jRadioButton15 = new JRadioButton();let jRadioButton15 = this.jRadioButton15;
    this.jProgressBar1 = new JProgressBar();let jProgressBar1 = this.jProgressBar1;
    this.jTabbedPane1 = new JTabbedPane();let jTabbedPane1 = this.jTabbedPane1;
    this.jPanel2 = new JPanel();let jPanel2 = this.jPanel2;
    this.jPanel3 = new JPanel();let jPanel3 = this.jPanel3;
    this.jPanel4 = new JPanel();let jPanel4 = this.jPanel4;
    this.jLabel1 = new JLabel();let jLabel1 = this.jLabel1;
    this.jSlider1 = new JSlider();let jSlider1 = this.jSlider1;
    this.setTitle("Test Roundness");
    this.getContentPane().setLayout(new BorderLayout(5, 5));
    jButton1.setText("jButton1");
    jButton1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton1);
    jButton9.setText("jButton1");
    jButton9.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jButton9ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jButton9);
    jPanel1.add(jComboBox1);
    jPanel1.add(jSpinner1);
    jTextField1.setText("jTextField1");
    jTextField1.addActionListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jTextField1ActionPerformed(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel1.add(jTextField1);
    jToggleButton1.setText("jToggleButton1");
    jPanel1.add(jToggleButton1);
    jToggleButton9.setText("jToggleButton1");
    jPanel1.add(jToggleButton9);
    buttonGroup2.add(jRadioButton9);
    jRadioButton9.setText("jRadioButton9");
    jRadioButton9.setContentAreaFilled(false);
    jPanel1.add(jRadioButton9);
    buttonGroup2.add(jRadioButton15);
    jRadioButton15.setText("jRadioButton9");
    jRadioButton15.setContentAreaFilled(false);
    jPanel1.add(jRadioButton15);
    this.getContentPane().add(jPanel1, BorderLayout.PAGE_END);
    jProgressBar1.setOrientation(1);
    jProgressBar1.setValue(35);
    jProgressBar1.setStringPainted(true);
    this.getContentPane().add(jProgressBar1, BorderLayout.LINE_END);
    jTabbedPane1.addTab("tab1 hello", jPanel2);
    jTabbedPane1.addTab("tab2", jPanel3);
    this.getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
    jPanel4.setLayout(new BorderLayout());
    jLabel1.setText("0.5");
    jPanel4.add(jLabel1, BorderLayout.CENTER);
    jSlider1.addChangeListener((p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) => this.jSlider1StateChanged(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
    jPanel4.add(jSlider1, BorderLayout.SOUTH);
    this.getContentPane().add(jPanel4, BorderLayout.NORTH);
  }

  // </editor-fold>//GEN-END:initComponents
   jButton1ActionPerformed(evt) {
    // GEN-FIRST:event_jButton1ActionPerformed
    console.log("OK!!!");
  }

  // GEN-LAST:event_jButton1ActionPerformed
   jButton9ActionPerformed(evt) {
    // GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
  }

  // GEN-LAST:event_jButton9ActionPerformed
   jTextField1ActionPerformed(evt) {
    // GEN-FIRST:event_jTextField1ActionPerformed
  }

  // GEN-LAST:event_jTextField1ActionPerformed
   jSlider1StateChanged(evt) {
    // GEN-FIRST:event_jSlider1StateChanged
    let v = this.jSlider1.getValue() / 100.0;
    this.jLabel1.setText("" + v);
    document.head.removeChild(document.head.querySelector("style"));
    SwingJS.instance().roundness(v).build();
  }

  // GEN-LAST:event_jSlider1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
   buttonGroup2 = null;

   jButton1 = null;

   jButton9 = null;

   jComboBox1 = null;

   jLabel1 = null;

   jPanel1 = null;

   jPanel2 = null;

   jPanel3 = null;

   jPanel4 = null;

   jProgressBar1 = null;

   jRadioButton15 = null;

   jRadioButton9 = null;

   jSlider1 = null;

   jSpinner1 = null;

   jTabbedPane1 = null;

   jTextField1 = null;

   jToggleButton1 = null;

   jToggleButton9 = null;
  // End of variables declaration//GEN-END:variables
}
